import oracledb from 'oracledb';
import dotenv from 'dotenv';
import path from 'path';
import bcrypt from 'bcrypt';

// Carregar variáveis de ambiente
const envPath = path.resolve(__dirname, '../../.env');
dotenv.config({ path: envPath });

async function createDatabaseSchema() {
  let connection: oracledb.Connection | undefined;
  
  try {
    console.log('🏗️  Criando estrutura completa do banco de dados...');
    
    // Configuração da conexão
    const config = {
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECT_STRING
    };
    
    console.log(`📋 Conectando como: ${config.user}@${config.connectString}`);
    
    // Conectar ao banco
    connection = await oracledb.getConnection(config);
    console.log('✅ Conexão estabelecida com sucesso!');
    
    // 1. Criar tabela de usuários
    console.log('\n👥 Criando tabela USERS...');
    await connection.execute(`
      CREATE TABLE users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR2(255) NOT NULL UNIQUE,
        password_hash VARCHAR2(255) NOT NULL,
        name VARCHAR2(255) NOT NULL,
        role VARCHAR2(50) DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER', 'MANAGER')),
        department VARCHAR2(100),
        phone VARCHAR2(20),
        is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        last_login TIMESTAMP
      )
    `);
    console.log('✅ Tabela USERS criada');
    
    // 2. Criar sequência para processos
    console.log('\n🔢 Criando sequência PROCESS_SEQ...');
    await connection.execute(`
      CREATE SEQUENCE process_seq
      START WITH 1
      INCREMENT BY 1
      NOCACHE
    `);
    console.log('✅ Sequência PROCESS_SEQ criada');
    
    // 3. Criar tabela de processos
    console.log('\n📋 Criando tabela PROCESSES...');
    await connection.execute(`
      CREATE TABLE processes (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        protocol_number VARCHAR2(50) NOT NULL UNIQUE,
        title VARCHAR2(500) NOT NULL,
        description CLOB,
        requester_name VARCHAR2(255) NOT NULL,
        requester_email VARCHAR2(255),
        requester_phone VARCHAR2(20),
        requester_document VARCHAR2(20),
        status VARCHAR2(50) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ARCHIVED')),
        priority VARCHAR2(20) DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
        category VARCHAR2(100),
        department VARCHAR2(100),
        assigned_to NUMBER,
        created_by NUMBER NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        due_date DATE,
        completed_at TIMESTAMP,
        CONSTRAINT fk_process_assigned_to FOREIGN KEY (assigned_to) REFERENCES users(id),
        CONSTRAINT fk_process_created_by FOREIGN KEY (created_by) REFERENCES users(id)
      )
    `);
    console.log('✅ Tabela PROCESSES criada');
    
    // 4. Criar tabela de documentos
    console.log('\n📄 Criando tabela DOCUMENTS...');
    await connection.execute(`
      CREATE TABLE documents (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        process_id NUMBER NOT NULL,
        filename VARCHAR2(255) NOT NULL,
        original_filename VARCHAR2(255) NOT NULL,
        file_path VARCHAR2(500) NOT NULL,
        file_size NUMBER,
        mime_type VARCHAR2(100),
        description VARCHAR2(500),
        uploaded_by NUMBER NOT NULL,
        uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
        CONSTRAINT fk_document_process FOREIGN KEY (process_id) REFERENCES processes(id) ON DELETE CASCADE,
        CONSTRAINT fk_document_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id)
      )
    `);
    console.log('✅ Tabela DOCUMENTS criada');
    
    // 5. Criar tabela de histórico/tramitação
    console.log('\n📝 Criando tabela PROCESS_HISTORY...');
    await connection.execute(`
      CREATE TABLE process_history (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        process_id NUMBER NOT NULL,
        action VARCHAR2(100) NOT NULL,
        description CLOB,
        old_status VARCHAR2(50),
        new_status VARCHAR2(50),
        old_assigned_to NUMBER,
        new_assigned_to NUMBER,
        created_by NUMBER NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_history_process FOREIGN KEY (process_id) REFERENCES processes(id) ON DELETE CASCADE,
        CONSTRAINT fk_history_created_by FOREIGN KEY (created_by) REFERENCES users(id),
        CONSTRAINT fk_history_old_assigned FOREIGN KEY (old_assigned_to) REFERENCES users(id),
        CONSTRAINT fk_history_new_assigned FOREIGN KEY (new_assigned_to) REFERENCES users(id)
      )
    `);
    console.log('✅ Tabela PROCESS_HISTORY criada');
    
    // 6. Criar tabela de comentários
    console.log('\n💬 Criando tabela PROCESS_COMMENTS...');
    await connection.execute(`
      CREATE TABLE process_comments (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        process_id NUMBER NOT NULL,
        comment_text CLOB NOT NULL,
        is_internal NUMBER(1) DEFAULT 0 CHECK (is_internal IN (0, 1)),
        created_by NUMBER NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_comment_process FOREIGN KEY (process_id) REFERENCES processes(id) ON DELETE CASCADE,
        CONSTRAINT fk_comment_created_by FOREIGN KEY (created_by) REFERENCES users(id)
      )
    `);
    console.log('✅ Tabela PROCESS_COMMENTS criada');
    
    // 7. Criar tabela de configurações do sistema
    console.log('\n⚙️  Criando tabela SYSTEM_SETTINGS...');
    await connection.execute(`
      CREATE TABLE system_settings (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        setting_key VARCHAR2(100) NOT NULL UNIQUE,
        setting_value CLOB,
        description VARCHAR2(500),
        is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
    console.log('✅ Tabela SYSTEM_SETTINGS criada');
    
    // 8. Criar índices para performance
    console.log('\n🚀 Criando índices para performance...');
    
    const indexes = [
      { name: 'idx_processes_status', sql: 'CREATE INDEX idx_processes_status ON processes(status)' },
      { name: 'idx_processes_created_by', sql: 'CREATE INDEX idx_processes_created_by ON processes(created_by)' },
      { name: 'idx_processes_assigned_to', sql: 'CREATE INDEX idx_processes_assigned_to ON processes(assigned_to)' },
      { name: 'idx_processes_protocol', sql: 'CREATE INDEX idx_processes_protocol ON processes(protocol_number)' },
      { name: 'idx_documents_process', sql: 'CREATE INDEX idx_documents_process ON documents(process_id)' },
      { name: 'idx_history_process', sql: 'CREATE INDEX idx_history_process ON process_history(process_id)' },
      { name: 'idx_comments_process', sql: 'CREATE INDEX idx_comments_process ON process_comments(process_id)' }
    ];
    
    for (const index of indexes) {
      try {
        await connection.execute(index.sql);
        console.log(`   ✅ Índice ${index.name} criado`);
      } catch (error: any) {
        if (error.errorNum === 1408) {
          console.log(`   ⚠️  Índice ${index.name} já existe`);
        } else {
          console.log(`   ❌ Erro ao criar índice ${index.name}: ${error.message}`);
        }
      }
    }
    
    console.log('✅ Índices processados');
    
    // 9. Criar triggers para updated_at
    console.log('\n🔄 Criando triggers para atualização automática...');
    
    // Trigger para users
    await connection.execute(`
      CREATE OR REPLACE TRIGGER trg_users_updated_at
      BEFORE UPDATE ON users
      FOR EACH ROW
      BEGIN
        :NEW.updated_at := CURRENT_TIMESTAMP;
      END;
    `);
    
    // Trigger para processes
    await connection.execute(`
      CREATE OR REPLACE TRIGGER trg_processes_updated_at
      BEFORE UPDATE ON processes
      FOR EACH ROW
      BEGIN
        :NEW.updated_at := CURRENT_TIMESTAMP;
      END;
    `);
    
    // Trigger para process_comments
    await connection.execute(`
      CREATE OR REPLACE TRIGGER trg_comments_updated_at
      BEFORE UPDATE ON process_comments
      FOR EACH ROW
      BEGIN
        :NEW.updated_at := CURRENT_TIMESTAMP;
      END;
    `);
    
    // Trigger para system_settings
    await connection.execute(`
      CREATE OR REPLACE TRIGGER trg_settings_updated_at
      BEFORE UPDATE ON system_settings
      FOR EACH ROW
      BEGIN
        :NEW.updated_at := CURRENT_TIMESTAMP;
      END;
    `);
    
    console.log('✅ Triggers criados');
    
    // 10. Inserir usuário administrador
    console.log('\n👤 Criando usuário administrador...');
    
    const adminEmail = 'admin_protocolo@sefaz.to.gov.br';
    const adminPassword = 'admin_protocolo123';
    const hashedPassword = await bcrypt.hash(adminPassword, 10);
    
    await connection.execute(
      `INSERT INTO users (email, password_hash, name, role, department, is_active) 
       VALUES (:email, :password_hash, :name, :role, :department, :is_active)`,
      {
        email: adminEmail,
        password_hash: hashedPassword,
        name: 'Administrador do Sistema',
        role: 'ADMIN',
        department: 'TI - SEFAZ',
        is_active: 1
      }
    );
    
    console.log(`✅ Usuário administrador criado: ${adminEmail}`);
    
    // 11. Inserir configurações iniciais do sistema
    console.log('\n⚙️  Inserindo configurações iniciais...');
    
    const initialSettings = [
      { key: 'SYSTEM_NAME', value: 'Sistema de Protocolo SEFAZ-TO', description: 'Nome do sistema' },
      { key: 'PROTOCOL_PREFIX', value: 'PROT', description: 'Prefixo para números de protocolo' },
      { key: 'MAX_FILE_SIZE', value: '10485760', description: 'Tamanho máximo de arquivo em bytes (10MB)' },
      { key: 'ALLOWED_FILE_TYPES', value: 'pdf,doc,docx,jpg,jpeg,png,txt', description: 'Tipos de arquivo permitidos' },
      { key: 'DEFAULT_PROCESS_PRIORITY', value: 'MEDIUM', description: 'Prioridade padrão para novos processos' },
      { key: 'NOTIFICATION_EMAIL', value: 'protocolo@sefaz.to.gov.br', description: 'Email para notificações do sistema' }
    ];
    
    for (const setting of initialSettings) {
      await connection.execute(
        `INSERT INTO system_settings (setting_key, setting_value, description) 
         VALUES (:key, :value, :description)`,
        {
          key: setting.key,
          value: setting.value,
          description: setting.description
        }
      );
    }
    
    console.log('✅ Configurações iniciais inseridas');
    
    // Commit das transações
    await connection.commit();
    console.log('\n💾 Todas as alterações foram salvas no banco');
    
    console.log('\n🎉 Estrutura do banco de dados criada com sucesso!');
    console.log('\n📋 Resumo das tabelas criadas:');
    console.log('   👥 USERS - Usuários do sistema');
    console.log('   📋 PROCESSES - Processos/protocolos');
    console.log('   📄 DOCUMENTS - Documentos anexados');
    console.log('   📝 PROCESS_HISTORY - Histórico de tramitação');
    console.log('   💬 PROCESS_COMMENTS - Comentários dos processos');
    console.log('   ⚙️  SYSTEM_SETTINGS - Configurações do sistema');
    
    console.log('\n🔑 Credenciais do administrador:');
    console.log(`   📧 Email: ${adminEmail}`);
    console.log(`   🔒 Senha: ${adminPassword}`);
    
  } catch (error: any) {
    console.error('❌ Erro ao criar estrutura do banco:', error.message);
    if (connection) {
      try {
        await connection.rollback();
        console.log('🔄 Rollback executado');
      } catch (rollbackError: any) {
        console.error('❌ Erro no rollback:', rollbackError.message);
      }
    }
    throw error;
  } finally {
    if (connection) {
      try {
        await connection.close();
        console.log('🔌 Conexão fechada');
      } catch (error: any) {
        console.error('❌ Erro ao fechar conexão:', error.message);
      }
    }
  }
}

// Executar criação do schema
createDatabaseSchema().catch(console.error);