ALTER SESSION SET CONTAINER=XEPDB1;
CREATE USER protocolo_user IDENTIFIED BY "Protocolo@2025";
GRANT CONNECT, RESOURCE, DBA TO protocolo_user;
ALTER USER protocolo_user QUOTA UNLIMITED ON USERS;
EXIT;