-- =====================================================
-- SISTEMA DE PROTOCOLO - CRIAÇÃO DE TABELAS ORACLE
-- =====================================================
-- Autor: Sistema Automatizado
-- Data: 2024
-- Descrição: Script para criação das tabelas principais
-- =====================================================

-- Configurações iniciais
SET SERVEROUTPUT ON;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

-- =====================================================
-- SEQUÊNCIAS PARA AUTO INCREMENT
-- =====================================================

-- Sequência para usuários
CREATE SEQUENCE SEQ_USUARIOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequência para processos
CREATE SEQUENCE SEQ_PROCESSOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequência para tramitações
CREATE SEQUENCE SEQ_TRAMITACOES
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequência para anexos
CREATE SEQUENCE SEQ_ANEXOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequência para logs de auditoria
CREATE SEQUENCE SEQ_LOGS_AUDITORIA
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- =====================================================
-- TABELA: USUARIOS
-- =====================================================
CREATE TABLE USUARIOS (
  ID NUMBER(10) PRIMARY KEY,
  NOME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(150) UNIQUE NOT NULL,
  SENHA VARCHAR2(255) NOT NULL,
  CPF VARCHAR2(14) UNIQUE,
  TELEFONE VARCHAR2(20),
  CARGO VARCHAR2(100),
  DEPARTAMENTO VARCHAR2(100),
  PERFIL VARCHAR2(20) DEFAULT 'USER' CHECK (PERFIL IN ('ADMIN', 'SUPERVISOR', 'USER')),
  STATUS VARCHAR2(20) DEFAULT 'ATIVO' CHECK (STATUS IN ('ATIVO', 'INATIVO', 'BLOQUEADO')),
  ULTIMO_LOGIN DATE,
  TENTATIVAS_LOGIN NUMBER(2) DEFAULT 0,
  TOKEN_RESET VARCHAR2(255),
  TOKEN_RESET_EXPIRA DATE,
  CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
  ATUALIZADO_EM DATE DEFAULT SYSDATE NOT NULL,
  CRIADO_POR NUMBER(10),
  ATUALIZADO_POR NUMBER(10)
);

-- Índices para USUARIOS
CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(EMAIL);
CREATE INDEX IDX_USUARIOS_CPF ON USUARIOS(CPF);
CREATE INDEX IDX_USUARIOS_STATUS ON USUARIOS(STATUS);
CREATE INDEX IDX_USUARIOS_DEPARTAMENTO ON USUARIOS(DEPARTAMENTO);

-- =====================================================
-- TABELA: PROCESSOS
-- =====================================================
CREATE TABLE PROCESSOS (
  ID NUMBER(10) PRIMARY KEY,
  NUMERO_PROCESSO VARCHAR2(50) UNIQUE NOT NULL,
  TITULO VARCHAR2(200) NOT NULL,
  DESCRICAO CLOB,
  TIPO_PROCESSO VARCHAR2(100) NOT NULL,
  CATEGORIA VARCHAR2(100),
  PRIORIDADE VARCHAR2(20) DEFAULT 'NORMAL' CHECK (PRIORIDADE IN ('BAIXA', 'NORMAL', 'ALTA', 'URGENTE')),
  STATUS VARCHAR2(30) DEFAULT 'ABERTO' CHECK (STATUS IN ('ABERTO', 'EM_ANDAMENTO', 'PENDENTE', 'CONCLUIDO', 'ARQUIVADO', 'CANCELADO')),
  DATA_ABERTURA DATE DEFAULT SYSDATE NOT NULL,
  DATA_PRAZO DATE,
  DATA_CONCLUSAO DATE,
  SETOR_ORIGEM VARCHAR2(100) NOT NULL,
  SETOR_ATUAL VARCHAR2(100) NOT NULL,
  RESPONSAVEL_ID NUMBER(10),
  CRIADOR_ID NUMBER(10) NOT NULL,
  OBSERVACOES CLOB,
  PALAVRAS_CHAVE VARCHAR2(500),
  VALOR_ESTIMADO NUMBER(15,2),
  CONFIDENCIAL CHAR(1) DEFAULT 'N' CHECK (CONFIDENCIAL IN ('S', 'N')),
  CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
  ATUALIZADO_EM DATE DEFAULT SYSDATE NOT NULL,
  ATUALIZADO_POR NUMBER(10)
);

-- Índices para PROCESSOS
CREATE INDEX IDX_PROCESSOS_NUMERO ON PROCESSOS(NUMERO_PROCESSO);
CREATE INDEX IDX_PROCESSOS_STATUS ON PROCESSOS(STATUS);
CREATE INDEX IDX_PROCESSOS_PRIORIDADE ON PROCESSOS(PRIORIDADE);
CREATE INDEX IDX_PROCESSOS_RESPONSAVEL ON PROCESSOS(RESPONSAVEL_ID);
CREATE INDEX IDX_PROCESSOS_CRIADOR ON PROCESSOS(CRIADOR_ID);
CREATE INDEX IDX_PROCESSOS_SETOR_ATUAL ON PROCESSOS(SETOR_ATUAL);
CREATE INDEX IDX_PROCESSOS_DATA_ABERTURA ON PROCESSOS(DATA_ABERTURA);
CREATE INDEX IDX_PROCESSOS_DATA_PRAZO ON PROCESSOS(DATA_PRAZO);
CREATE INDEX IDX_PROCESSOS_TIPO ON PROCESSOS(TIPO_PROCESSO);

-- =====================================================
-- TABELA: TRAMITACOES
-- =====================================================
CREATE TABLE TRAMITACOES (
  ID NUMBER(10) PRIMARY KEY,
  PROCESSO_ID NUMBER(10) NOT NULL,
  SETOR_ORIGEM VARCHAR2(100) NOT NULL,
  SETOR_DESTINO VARCHAR2(100) NOT NULL,
  USUARIO_ORIGEM_ID NUMBER(10) NOT NULL,
  USUARIO_DESTINO_ID NUMBER(10),
  DATA_TRAMITACAO DATE DEFAULT SYSDATE NOT NULL,
  DATA_RECEBIMENTO DATE,
  OBSERVACOES CLOB,
  TIPO_TRAMITACAO VARCHAR2(50) DEFAULT 'ENCAMINHAMENTO' CHECK (TIPO_TRAMITACAO IN ('ENCAMINHAMENTO', 'DEVOLUCAO', 'ARQUIVAMENTO', 'DESARQUIVAMENTO')),
  STATUS VARCHAR2(20) DEFAULT 'ENVIADO' CHECK (STATUS IN ('ENVIADO', 'RECEBIDO', 'REJEITADO')),
  PRAZO_RESPOSTA DATE,
  URGENTE CHAR(1) DEFAULT 'N' CHECK (URGENTE IN ('S', 'N')),
  CRIADO_EM DATE DEFAULT SYSDATE NOT NULL
);

-- Índices para TRAMITACOES
CREATE INDEX IDX_TRAMITACOES_PROCESSO ON TRAMITACOES(PROCESSO_ID);
CREATE INDEX IDX_TRAMITACOES_ORIGEM ON TRAMITACOES(USUARIO_ORIGEM_ID);
CREATE INDEX IDX_TRAMITACOES_DESTINO ON TRAMITACOES(USUARIO_DESTINO_ID);
CREATE INDEX IDX_TRAMITACOES_DATA ON TRAMITACOES(DATA_TRAMITACAO);
CREATE INDEX IDX_TRAMITACOES_STATUS ON TRAMITACOES(STATUS);
CREATE INDEX IDX_TRAMITACOES_SETOR_DEST ON TRAMITACOES(SETOR_DESTINO);

-- =====================================================
-- TABELA: ANEXOS
-- =====================================================
CREATE TABLE ANEXOS (
  ID NUMBER(10) PRIMARY KEY,
  PROCESSO_ID NUMBER(10) NOT NULL,
  TRAMITACAO_ID NUMBER(10),
  NOME_ARQUIVO VARCHAR2(255) NOT NULL,
  NOME_ORIGINAL VARCHAR2(255) NOT NULL,
  TIPO_ARQUIVO VARCHAR2(100),
  TAMANHO_ARQUIVO NUMBER(15),
  CAMINHO_ARQUIVO VARCHAR2(500) NOT NULL,
  HASH_ARQUIVO VARCHAR2(64),
  DESCRICAO VARCHAR2(500),
  PUBLICO CHAR(1) DEFAULT 'N' CHECK (PUBLICO IN ('S', 'N')),
  USUARIO_UPLOAD_ID NUMBER(10) NOT NULL,
  DATA_UPLOAD DATE DEFAULT SYSDATE NOT NULL,
  CRIADO_EM DATE DEFAULT SYSDATE NOT NULL
);

-- Índices para ANEXOS
CREATE INDEX IDX_ANEXOS_PROCESSO ON ANEXOS(PROCESSO_ID);
CREATE INDEX IDX_ANEXOS_TRAMITACAO ON ANEXOS(TRAMITACAO_ID);
CREATE INDEX IDX_ANEXOS_USUARIO ON ANEXOS(USUARIO_UPLOAD_ID);
CREATE INDEX IDX_ANEXOS_DATA ON ANEXOS(DATA_UPLOAD);
CREATE INDEX IDX_ANEXOS_TIPO ON ANEXOS(TIPO_ARQUIVO);

-- =====================================================
-- TABELA: LOGS_AUDITORIA
-- =====================================================
CREATE TABLE LOGS_AUDITORIA (
  ID NUMBER(10) PRIMARY KEY,
  TABELA VARCHAR2(50) NOT NULL,
  REGISTRO_ID NUMBER(10) NOT NULL,
  OPERACAO VARCHAR2(20) NOT NULL CHECK (OPERACAO IN ('INSERT', 'UPDATE', 'DELETE')),
  DADOS_ANTERIORES CLOB,
  DADOS_NOVOS CLOB,
  USUARIO_ID NUMBER(10),
  IP_USUARIO VARCHAR2(45),
  USER_AGENT VARCHAR2(500),
  DATA_OPERACAO DATE DEFAULT SYSDATE NOT NULL,
  OBSERVACOES VARCHAR2(500)
);

-- Índices para LOGS_AUDITORIA
CREATE INDEX IDX_LOGS_TABELA ON LOGS_AUDITORIA(TABELA);
CREATE INDEX IDX_LOGS_REGISTRO ON LOGS_AUDITORIA(REGISTRO_ID);
CREATE INDEX IDX_LOGS_USUARIO ON LOGS_AUDITORIA(USUARIO_ID);
CREATE INDEX IDX_LOGS_DATA ON LOGS_AUDITORIA(DATA_OPERACAO);
CREATE INDEX IDX_LOGS_OPERACAO ON LOGS_AUDITORIA(OPERACAO);

-- =====================================================
-- TABELA: SETORES
-- =====================================================
CREATE TABLE SETORES (
  ID NUMBER(10) PRIMARY KEY,
  NOME VARCHAR2(100) UNIQUE NOT NULL,
  SIGLA VARCHAR2(20) UNIQUE NOT NULL,
  DESCRICAO VARCHAR2(500),
  RESPONSAVEL_ID NUMBER(10),
  SETOR_PAI_ID NUMBER(10),
  ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
  ORDEM_EXIBICAO NUMBER(3),
  CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
  ATUALIZADO_EM DATE DEFAULT SYSDATE NOT NULL
);

-- Sequência para setores
CREATE SEQUENCE SEQ_SETORES
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Índices para SETORES
CREATE INDEX IDX_SETORES_NOME ON SETORES(NOME);
CREATE INDEX IDX_SETORES_SIGLA ON SETORES(SIGLA);
CREATE INDEX IDX_SETORES_RESPONSAVEL ON SETORES(RESPONSAVEL_ID);
CREATE INDEX IDX_SETORES_PAI ON SETORES(SETOR_PAI_ID);
CREATE INDEX IDX_SETORES_ATIVO ON SETORES(ATIVO);

-- =====================================================
-- TABELA: TIPOS_PROCESSO
-- =====================================================
CREATE TABLE TIPOS_PROCESSO (
  ID NUMBER(10) PRIMARY KEY,
  NOME VARCHAR2(100) UNIQUE NOT NULL,
  DESCRICAO VARCHAR2(500),
  PRAZO_PADRAO_DIAS NUMBER(3),
  REQUER_APROVACAO CHAR(1) DEFAULT 'N' CHECK (REQUER_APROVACAO IN ('S', 'N')),
  ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
  CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
  ATUALIZADO_EM DATE DEFAULT SYSDATE NOT NULL
);

-- Sequência para tipos de processo
CREATE SEQUENCE SEQ_TIPOS_PROCESSO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Índices para TIPOS_PROCESSO
CREATE INDEX IDX_TIPOS_PROCESSO_NOME ON TIPOS_PROCESSO(NOME);
CREATE INDEX IDX_TIPOS_PROCESSO_ATIVO ON TIPOS_PROCESSO(ATIVO);

-- =====================================================
-- CHAVES ESTRANGEIRAS
-- =====================================================

-- Usuários
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_CRIADO_POR 
  FOREIGN KEY (CRIADO_POR) REFERENCES USUARIOS(ID);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_ATUALIZADO_POR 
  FOREIGN KEY (ATUALIZADO_POR) REFERENCES USUARIOS(ID);

-- Processos
ALTER TABLE PROCESSOS ADD CONSTRAINT FK_PROCESSOS_RESPONSAVEL 
  FOREIGN KEY (RESPONSAVEL_ID) REFERENCES USUARIOS(ID);
ALTER TABLE PROCESSOS ADD CONSTRAINT FK_PROCESSOS_CRIADOR 
  FOREIGN KEY (CRIADOR_ID) REFERENCES USUARIOS(ID);
ALTER TABLE PROCESSOS ADD CONSTRAINT FK_PROCESSOS_ATUALIZADO_POR 
  FOREIGN KEY (ATUALIZADO_POR) REFERENCES USUARIOS(ID);

-- Tramitações
ALTER TABLE TRAMITACOES ADD CONSTRAINT FK_TRAMITACOES_PROCESSO 
  FOREIGN KEY (PROCESSO_ID) REFERENCES PROCESSOS(ID) ON DELETE CASCADE;
ALTER TABLE TRAMITACOES ADD CONSTRAINT FK_TRAMITACOES_ORIGEM 
  FOREIGN KEY (USUARIO_ORIGEM_ID) REFERENCES USUARIOS(ID);
ALTER TABLE TRAMITACOES ADD CONSTRAINT FK_TRAMITACOES_DESTINO 
  FOREIGN KEY (USUARIO_DESTINO_ID) REFERENCES USUARIOS(ID);

-- Anexos
ALTER TABLE ANEXOS ADD CONSTRAINT FK_ANEXOS_PROCESSO 
  FOREIGN KEY (PROCESSO_ID) REFERENCES PROCESSOS(ID) ON DELETE CASCADE;
ALTER TABLE ANEXOS ADD CONSTRAINT FK_ANEXOS_TRAMITACAO 
  FOREIGN KEY (TRAMITACAO_ID) REFERENCES TRAMITACOES(ID) ON DELETE CASCADE;
ALTER TABLE ANEXOS ADD CONSTRAINT FK_ANEXOS_USUARIO 
  FOREIGN KEY (USUARIO_UPLOAD_ID) REFERENCES USUARIOS(ID);

-- Logs de Auditoria
ALTER TABLE LOGS_AUDITORIA ADD CONSTRAINT FK_LOGS_USUARIO 
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID);

-- Setores
ALTER TABLE SETORES ADD CONSTRAINT FK_SETORES_RESPONSAVEL 
  FOREIGN KEY (RESPONSAVEL_ID) REFERENCES USUARIOS(ID);
ALTER TABLE SETORES ADD CONSTRAINT FK_SETORES_PAI 
  FOREIGN KEY (SETOR_PAI_ID) REFERENCES SETORES(ID);

-- =====================================================
-- TRIGGERS PARA AUTO INCREMENT
-- =====================================================

-- Trigger para USUARIOS
CREATE OR REPLACE TRIGGER TRG_USUARIOS_ID
  BEFORE INSERT ON USUARIOS
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SEQ_USUARIOS.NEXTVAL;
  END IF;
END;
/

-- Trigger para PROCESSOS
CREATE OR REPLACE TRIGGER TRG_PROCESSOS_ID
  BEFORE INSERT ON PROCESSOS
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SEQ_PROCESSOS.NEXTVAL;
  END IF;
END;
/

-- Trigger para TRAMITACOES
CREATE OR REPLACE TRIGGER TRG_TRAMITACOES_ID
  BEFORE INSERT ON TRAMITACOES
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SEQ_TRAMITACOES.NEXTVAL;
  END IF;
END;
/

-- Trigger para ANEXOS
CREATE OR REPLACE TRIGGER TRG_ANEXOS_ID
  BEFORE INSERT ON ANEXOS
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SEQ_ANEXOS.NEXTVAL;
  END IF;
END;
/

-- Trigger para LOGS_AUDITORIA
CREATE OR REPLACE TRIGGER TRG_LOGS_AUDITORIA_ID
  BEFORE INSERT ON LOGS_AUDITORIA
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SEQ_LOGS_AUDITORIA.NEXTVAL;
  END IF;
END;
/

-- Trigger para SETORES
CREATE OR REPLACE TRIGGER TRG_SETORES_ID
  BEFORE INSERT ON SETORES
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SEQ_SETORES.NEXTVAL;
  END IF;
END;
/

-- Trigger para TIPOS_PROCESSO
CREATE OR REPLACE TRIGGER TRG_TIPOS_PROCESSO_ID
  BEFORE INSERT ON TIPOS_PROCESSO
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SEQ_TIPOS_PROCESSO.NEXTVAL;
  END IF;
END;
/

-- =====================================================
-- TRIGGERS PARA AUDITORIA
-- =====================================================

-- Trigger para atualizar ATUALIZADO_EM em USUARIOS
CREATE OR REPLACE TRIGGER TRG_USUARIOS_UPDATED
  BEFORE UPDATE ON USUARIOS
  FOR EACH ROW
BEGIN
  :NEW.ATUALIZADO_EM := SYSDATE;
END;
/

-- Trigger para atualizar ATUALIZADO_EM em PROCESSOS
CREATE OR REPLACE TRIGGER TRG_PROCESSOS_UPDATED
  BEFORE UPDATE ON PROCESSOS
  FOR EACH ROW
BEGIN
  :NEW.ATUALIZADO_EM := SYSDATE;
END;
/

-- Trigger para atualizar ATUALIZADO_EM em SETORES
CREATE OR REPLACE TRIGGER TRG_SETORES_UPDATED
  BEFORE UPDATE ON SETORES
  FOR EACH ROW
BEGIN
  :NEW.ATUALIZADO_EM := SYSDATE;
END;
/

-- Trigger para atualizar ATUALIZADO_EM em TIPOS_PROCESSO
CREATE OR REPLACE TRIGGER TRG_TIPOS_PROCESSO_UPDATED
  BEFORE UPDATE ON TIPOS_PROCESSO
  FOR EACH ROW
BEGIN
  :NEW.ATUALIZADO_EM := SYSDATE;
END;
/

-- =====================================================
-- COMENTÁRIOS NAS TABELAS
-- =====================================================

COMMENT ON TABLE USUARIOS IS 'Tabela de usuários do sistema';
COMMENT ON TABLE PROCESSOS IS 'Tabela principal de processos';
COMMENT ON TABLE TRAMITACOES IS 'Histórico de tramitações dos processos';
COMMENT ON TABLE ANEXOS IS 'Arquivos anexados aos processos';
COMMENT ON TABLE LOGS_AUDITORIA IS 'Log de auditoria das operações';
COMMENT ON TABLE SETORES IS 'Setores/Departamentos da organização';
COMMENT ON TABLE TIPOS_PROCESSO IS 'Tipos de processo disponíveis';

-- =====================================================
-- FINALIZAÇÃO
-- =====================================================

PROMPT 'Tabelas criadas com sucesso!';
PROMPT 'Execute o próximo script: 02_insert_initial_data.sql';

COMMIT;