-- =====================================================
-- SCRIPT DE ALTERAÇÃO DA TABELA USUARIOS
-- Data: 11/09/2025
-- Objetivo: Adicionar novos campos para migração SEFAZ
-- =====================================================

-- Dados Pessoais Básicos
ALTER TABLE USUARIOS ADD CPF VARCHAR2(14);
ALTER TABLE USUARIOS ADD PIS_PASEP VARCHAR2(15);
ALTER TABLE USUARIOS ADD SEXO VARCHAR2(1);
ALTER TABLE USUARIOS ADD ESTADO_CIVIL VARCHAR2(20);
ALTER TABLE USUARIOS ADD DATA_NASCIMENTO DATE;
ALTER TABLE USUARIOS ADD NOME_PAI VARCHAR2(100);
ALTER TABLE USUARIOS ADD NOME_MAE VARCHAR2(100);
ALTER TABLE USUARIOS ADD RACA_COR VARCHAR2(20);
ALTER TABLE USUARIOS ADD TIPO_SANGUINEO VARCHAR2(5);

-- Documentação
ALTER TABLE USUARIOS ADD RG VARCHAR2(20);
ALTER TABLE USUARIOS ADD TIPO_RG VARCHAR2(20);
ALTER TABLE USUARIOS ADD ORGAO_EXPEDITOR VARCHAR2(50);
ALTER TABLE USUARIOS ADD UF_RG VARCHAR2(2);
ALTER TABLE USUARIOS ADD DATA_EXPEDICAO_RG DATE;

-- Dados Bancários
ALTER TABLE USUARIOS ADD BANCO VARCHAR2(100);
ALTER TABLE USUARIOS ADD AGENCIA VARCHAR2(10);
ALTER TABLE USUARIOS ADD CONTA VARCHAR2(20);

-- Informações Funcionais
ALTER TABLE USUARIOS ADD NUMERO_FUNCIONAL NUMBER(10);
ALTER TABLE USUARIOS ADD NUMERO_VINCULO NUMBER(10);
ALTER TABLE USUARIOS ADD CODIGO_CARGO NUMBER(10);
ALTER TABLE USUARIOS ADD CARGO VARCHAR2(100);
ALTER TABLE USUARIOS ADD TIPO_VINCULO VARCHAR2(50);
ALTER TABLE USUARIOS ADD CATEGORIA VARCHAR2(50);
ALTER TABLE USUARIOS ADD REGIME_JURIDICO VARCHAR2(50);
ALTER TABLE USUARIOS ADD REGIME_PREVIDENCIARIO VARCHAR2(50);
ALTER TABLE USUARIOS ADD SITUACAO VARCHAR2(20);
ALTER TABLE USUARIOS ADD JORNADA NUMBER(3);

-- Datas Importantes
ALTER TABLE USUARIOS ADD DATA_INGRESSO_SERVICO_PUBLICO DATE;
ALTER TABLE USUARIOS ADD DATA_INICIO_ATIVIDADE DATE;
ALTER TABLE USUARIOS ADD DATA_DESATIVACAO DATE;

-- Escolaridade e Formação
ALTER TABLE USUARIOS ADD ESCOLARIDADE_CARGO VARCHAR2(50);
ALTER TABLE USUARIOS ADD ESCOLARIDADE_SERVIDOR VARCHAR2(50);
ALTER TABLE USUARIOS ADD FORMACAO_PROFISSIONAL_1 VARCHAR2(100);
ALTER TABLE USUARIOS ADD FORMACAO_PROFISSIONAL_2 VARCHAR2(100);

-- Localização e Contato
ALTER TABLE USUARIOS ADD CIDADE_NASCIMENTO VARCHAR2(100);
ALTER TABLE USUARIOS ADD UF_NASCIMENTO VARCHAR2(2);
ALTER TABLE USUARIOS ADD MUNICIPIO_LOTACAO VARCHAR2(100);
ALTER TABLE USUARIOS ADD TELEFONE VARCHAR2(20);
ALTER TABLE USUARIOS ADD ENDERECO VARCHAR2(200);
ALTER TABLE USUARIOS ADD NUMERO_ENDERECO VARCHAR2(10);
ALTER TABLE USUARIOS ADD COMPLEMENTO_ENDERECO VARCHAR2(50);
ALTER TABLE USUARIOS ADD BAIRRO_ENDERECO VARCHAR2(100);
ALTER TABLE USUARIOS ADD CIDADE_ENDERECO VARCHAR2(100);
ALTER TABLE USUARIOS ADD UF_ENDERECO VARCHAR2(2);
ALTER TABLE USUARIOS ADD CEP_ENDERECO VARCHAR2(9);

-- Estrutura Organizacional
ALTER TABLE USUARIOS ADD ORGAO VARCHAR2(100);
ALTER TABLE USUARIOS ADD LOTACAO VARCHAR2(200);
ALTER TABLE USUARIOS ADD HIERARQUIA_SETOR VARCHAR2(500);

-- Remuneração
ALTER TABLE USUARIOS ADD NIVEL_REFERENCIA VARCHAR2(20);
ALTER TABLE USUARIOS ADD VALOR_NIVEL_REFERENCIA NUMBER(10,2);
ALTER TABLE USUARIOS ADD COMISSAO_FUNCAO VARCHAR2(100);
ALTER TABLE USUARIOS ADD SIMBOLO VARCHAR2(20);
ALTER TABLE USUARIOS ADD VALOR_SIMBOLO NUMBER(10,2);

-- Acessibilidade
ALTER TABLE USUARIOS ADD PNE VARCHAR2(3);
ALTER TABLE USUARIOS ADD TIPO_DEFICIENCIA VARCHAR2(100);

-- Adicionar comentários aos campos
COMMENT ON COLUMN USUARIOS.CPF IS 'CPF do usuário - Campo sensível';
COMMENT ON COLUMN USUARIOS.NUMERO_FUNCIONAL IS 'Matrícula funcional do servidor';
COMMENT ON COLUMN USUARIOS.DATA_NASCIMENTO IS 'Data de nascimento do servidor';
COMMENT ON COLUMN USUARIOS.CARGO IS 'Cargo atual do servidor';
COMMENT ON COLUMN USUARIOS.SITUACAO IS 'Situação funcional do servidor';
COMMENT ON COLUMN USUARIOS.PNE IS 'Pessoa com Necessidades Especiais (SIM/NAO)';

PROMPT 'Novos campos adicionados à tabela USUARIOS com sucesso!';
PROMPT 'Total de campos adicionados: 52';

-- Verificar a estrutura atualizada
SELECT COUNT(*) AS TOTAL_COLUNAS 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS';