-- =====================================================
-- SCRIPT DE CRIAÇÃO DE ÍNDICES
-- Data: 11/09/2025
-- Objetivo: Criar índices para otimizar consultas
-- =====================================================

-- Índices únicos para campos de identificação
CREATE UNIQUE INDEX IDX_USUARIOS_CPF ON USUARIOS(CPF) WHERE CPF IS NOT NULL;
CREATE UNIQUE INDEX IDX_USUARIOS_NUMERO_FUNCIONAL ON USUARIOS(NUMERO_FUNCIONAL) WHERE NUMERO_FUNCIONAL IS NOT NULL;
CREATE UNIQUE INDEX IDX_USUARIOS_PIS_PASEP ON USUARIOS(PIS_PASEP) WHERE PIS_PASEP IS NOT NULL;

-- Índices para campos de consulta frequente
CREATE INDEX IDX_USUARIOS_NOME ON USUARIOS(UPPER(NOME));
CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(UPPER(EMAIL));
CREATE INDEX IDX_USUARIOS_CARGO ON USUARIOS(UPPER(CARGO));
CREATE INDEX IDX_USUARIOS_DEPARTAMENTO ON USUARIOS(UPPER(DEPARTAMENTO));
CREATE INDEX IDX_USUARIOS_ORGAO ON USUARIOS(UPPER(ORGAO));
CREATE INDEX IDX_USUARIOS_SITUACAO ON USUARIOS(SITUACAO);

-- Índices para datas
CREATE INDEX IDX_USUARIOS_DATA_NASCIMENTO ON USUARIOS(DATA_NASCIMENTO);
CREATE INDEX IDX_USUARIOS_DATA_INGRESSO ON USUARIOS(DATA_INGRESSO_SERVICO_PUBLICO);
CREATE INDEX IDX_USUARIOS_CREATED_AT ON USUARIOS(CREATED_AT);

-- Índices para localização
CREATE INDEX IDX_USUARIOS_UF_NASCIMENTO ON USUARIOS(UF_NASCIMENTO);
CREATE INDEX IDX_USUARIOS_CIDADE_NASCIMENTO ON USUARIOS(UPPER(CIDADE_NASCIMENTO));
CREATE INDEX IDX_USUARIOS_MUNICIPIO_LOTACAO ON USUARIOS(UPPER(MUNICIPIO_LOTACAO));

-- Índices compostos para consultas específicas
CREATE INDEX IDX_USUARIOS_ATIVO_SITUACAO ON USUARIOS(ATIVO, SITUACAO);
CREATE INDEX IDX_USUARIOS_CARGO_ORGAO ON USUARIOS(UPPER(CARGO), UPPER(ORGAO));
CREATE INDEX IDX_USUARIOS_PERFIL_ATIVO ON USUARIOS(PERFIL, ATIVO);

-- Índice para campos de endereço (consultas por localização)
CREATE INDEX IDX_USUARIOS_ENDERECO_COMPLETO ON USUARIOS(UPPER(CIDADE_ENDERECO), UF_ENDERECO, CEP_ENDERECO);

-- Índice para consultas por tipo de vínculo
CREATE INDEX IDX_USUARIOS_VINCULO_CATEGORIA ON USUARIOS(UPPER(TIPO_VINCULO), UPPER(CATEGORIA));

-- Índice para consultas por formação
CREATE INDEX IDX_USUARIOS_ESCOLARIDADE ON USUARIOS(UPPER(ESCOLARIDADE_SERVIDOR));

-- Índice para acessibilidade
CREATE INDEX IDX_USUARIOS_PNE ON USUARIOS(PNE) WHERE PNE IS NOT NULL;

-- Estatísticas dos índices criados
PROMPT 'Índices criados com sucesso!';
PROMPT 'Verificando índices da tabela USUARIOS:';

SELECT 
    INDEX_NAME,
    UNIQUENESS,
    STATUS
FROM USER_INDEXES 
WHERE TABLE_NAME = 'USUARIOS'
ORDER BY INDEX_NAME;

PROMPT 'Coletando estatísticas para otimização:';

-- Coletar estatísticas para otimização do Oracle
EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'USUARIOS', CASCADE => TRUE);

PROMPT 'Estatísticas coletadas. Índices prontos para uso!';

-- Verificar o tamanho da tabela após as alterações
SELECT 
    ROUND(SUM(BYTES)/1024/1024, 2) AS SIZE_MB
FROM USER_SEGMENTS 
WHERE SEGMENT_NAME = 'USUARIOS';