-- =====================================================
-- TABELA DE CONFIGURAÇÕES DO SISTEMA
-- =====================================================
-- Autor: Sistema Automatizado
-- Data: 2024
-- Descrição: Tabela para armazenar configurações dinâmicas do sistema
-- =====================================================

-- Configurações iniciais
SET SERVEROUTPUT ON;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

-- =====================================================
-- TABELA: CONFIGURACOES
-- =====================================================
CREATE TABLE CONFIGURACOES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CATEGORIA VARCHAR2(50) NOT NULL, -- 'geral', 'seguranca', 'notificacoes', 'sistema', 'aparencia'
    CHAVE VARCHAR2(100) NOT NULL, -- nome_instituicao, cnpj, endereco, etc.
    VALOR CLOB, -- Valor da configuração (pode ser texto, JSON, etc.)
    TIPO VARCHAR2(20) DEFAULT 'string' CHECK (TIPO IN ('string', 'number', 'boolean', 'json', 'date')),
    DESCRICAO VARCHAR2(500), -- Descrição da configuração
    OBRIGATORIA CHAR(1) DEFAULT 'N' CHECK (OBRIGATORIA IN ('S', 'N')),
    EDITAVEL CHAR(1) DEFAULT 'S' CHECK (EDITAVEL IN ('S', 'N')),
    ORDEM_EXIBICAO NUMBER(3) DEFAULT 0,
    USUARIO_CRIACAO_ID NUMBER,
    USUARIO_ALTERACAO_ID NUMBER,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    
    -- Constraints
    CONSTRAINT UK_CONFIG_CATEGORIA_CHAVE UNIQUE (CATEGORIA, CHAVE),
    CONSTRAINT FK_CONFIG_USER_CRIACAO FOREIGN KEY (USUARIO_CRIACAO_ID) REFERENCES USUARIOS(ID),
    CONSTRAINT FK_CONFIG_USER_ALTERACAO FOREIGN KEY (USUARIO_ALTERACAO_ID) REFERENCES USUARIOS(ID)
);

-- =====================================================
-- ÍNDICES PARA PERFORMANCE
-- =====================================================
CREATE INDEX IDX_CONFIGURACOES_CATEGORIA ON CONFIGURACOES(CATEGORIA);
CREATE INDEX IDX_CONFIGURACOES_CHAVE ON CONFIGURACOES(CHAVE);
CREATE INDEX IDX_CONFIGURACOES_ATIVO ON CONFIGURACOES(ATIVO);
CREATE INDEX IDX_CONFIGURACOES_CATEGORIA_CHAVE ON CONFIGURACOES(CATEGORIA, CHAVE);

-- =====================================================
-- TRIGGER PARA ATUALIZAR DATA_ALTERACAO
-- =====================================================
CREATE OR REPLACE TRIGGER TRG_CONFIGURACOES_UPDATE
    BEFORE UPDATE ON CONFIGURACOES
    FOR EACH ROW
BEGIN
    :NEW.DATA_ALTERACAO := CURRENT_TIMESTAMP;
END;
/

-- =====================================================
-- INSERIR CONFIGURAÇÕES PADRÃO
-- =====================================================

-- Configurações Gerais
INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('geral', 'nome_instituicao', 'Prefeitura Municipal', 'string', 'Nome da instituição', 'S', 1);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('geral', 'cnpj', '00.000.000/0001-00', 'string', 'CNPJ da instituição', 'S', 2);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('geral', 'endereco', 'Av. Principal, 123 - Centro', 'string', 'Endereço da instituição', 'N', 3);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('geral', 'telefone', '(63) 3000-0000', 'string', 'Telefone institucional', 'N', 4);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('geral', 'email_institucional', 'contato@prefeitura.gov.br', 'string', 'E-mail institucional', 'S', 5);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('geral', 'descricao', 'Sistema de gestão administrativa municipal', 'string', 'Descrição da instituição', 'N', 6);

-- Configurações de Segurança
INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('seguranca', 'sessao_timeout', '30', 'number', 'Timeout da sessão em minutos', 'S', 1);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('seguranca', 'tentativas_login', '5', 'number', 'Máximo de tentativas de login', 'S', 2);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('seguranca', 'senha_minima_caracteres', '8', 'number', 'Mínimo de caracteres na senha', 'S', 3);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('seguranca', 'senha_requer_maiuscula', 'true', 'boolean', 'Senha deve ter letra maiúscula', 'S', 4);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('seguranca', 'senha_requer_numero', 'true', 'boolean', 'Senha deve ter número', 'S', 5);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('seguranca', 'senha_requer_simbolo', 'false', 'boolean', 'Senha deve ter símbolo especial', 'N', 6);

-- Configurações de Notificações
INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('notificacoes', 'email_habilitado', 'true', 'boolean', 'Habilitar notificações por email', 'N', 1);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('notificacoes', 'email_servidor_smtp', 'smtp.gmail.com', 'string', 'Servidor SMTP', 'N', 2);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('notificacoes', 'email_porta', '587', 'number', 'Porta do servidor SMTP', 'N', 3);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('notificacoes', 'notificar_novos_processos', 'true', 'boolean', 'Notificar sobre novos processos', 'N', 4);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('notificacoes', 'notificar_prazos_vencendo', 'true', 'boolean', 'Notificar prazos próximos do vencimento', 'N', 5);

-- Configurações do Sistema
INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('sistema', 'backup_automatico', 'true', 'boolean', 'Backup automático diário', 'N', 1);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('sistema', 'log_nivel', 'info', 'string', 'Nível de log do sistema', 'S', 2);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('sistema', 'manutencao_modo', 'false', 'boolean', 'Modo de manutenção', 'N', 3);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('sistema', 'upload_tamanho_maximo', '10', 'number', 'Tamanho máximo de upload em MB', 'S', 4);

-- Configurações de Aparência
INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('aparencia', 'tema_padrao', 'claro', 'string', 'Tema padrão do sistema', 'N', 1);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('aparencia', 'cor_primaria', '#3B82F6', 'string', 'Cor primária do sistema', 'N', 2);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('aparencia', 'logo_url', '/assets/logo.png', 'string', 'URL do logo da instituição', 'N', 3);

INSERT INTO CONFIGURACOES (CATEGORIA, CHAVE, VALOR, TIPO, DESCRICAO, OBRIGATORIA, ORDEM_EXIBICAO) VALUES
('aparencia', 'favicon_url', '/assets/favicon.ico', 'string', 'URL do favicon', 'N', 4);

-- =====================================================
-- COMENTÁRIOS NA TABELA
-- =====================================================
COMMENT ON TABLE CONFIGURACOES IS 'Tabela de configurações dinâmicas do sistema';
COMMENT ON COLUMN CONFIGURACOES.CATEGORIA IS 'Categoria da configuração (geral, seguranca, notificacoes, sistema, aparencia)';
COMMENT ON COLUMN CONFIGURACOES.CHAVE IS 'Chave única da configuração dentro da categoria';
COMMENT ON COLUMN CONFIGURACOES.VALOR IS 'Valor da configuração (pode ser texto, JSON, etc.)';
COMMENT ON COLUMN CONFIGURACOES.TIPO IS 'Tipo do valor (string, number, boolean, json, date)';
COMMENT ON COLUMN CONFIGURACOES.DESCRICAO IS 'Descrição da configuração';
COMMENT ON COLUMN CONFIGURACOES.OBRIGATORIA IS 'Se a configuração é obrigatória (S/N)';
COMMENT ON COLUMN CONFIGURACOES.EDITAVEL IS 'Se a configuração pode ser editada (S/N)';
COMMENT ON COLUMN CONFIGURACOES.ORDEM_EXIBICAO IS 'Ordem de exibição na interface';

-- =====================================================
-- FINALIZAÇÃO
-- =====================================================
PROMPT 'Tabela CONFIGURACOES criada com sucesso!';
PROMPT 'Configurações padrão inseridas!';
PROMPT 'Execute o backend para testar a API de configurações.';

COMMIT;