-- =====================================================
-- CRIAÇÃO DE TABELAS FALTANTES - SISTEMA DE PROTOCOLO
-- =====================================================
-- Autor: Sistema Automatizado
-- Data: 2025
-- Descrição: Script para criar tabelas identificadas como faltantes
-- Tabelas: ENCOMENDAS, DOCUMENTOS, PRAZOS, CONFIGURACOES
-- =====================================================

-- Configurações iniciais
SET SERVEROUTPUT ON;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

-- =====================================================
-- SEQUÊNCIAS PARA AUTO INCREMENT
-- =====================================================

-- Sequência para encomendas
CREATE SEQUENCE SEQ_ENCOMENDAS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequência para documentos
CREATE SEQUENCE SEQ_DOCUMENTOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequência para prazos
CREATE SEQUENCE SEQ_PRAZOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Sequência para configurações
CREATE SEQUENCE SEQ_CONFIGURACOES
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- =====================================================
-- TABELA: ENCOMENDAS
-- =====================================================
CREATE TABLE ENCOMENDAS (
  ID NUMBER(10) PRIMARY KEY,
  CODIGO_RASTREAMENTO VARCHAR2(50) UNIQUE NOT NULL,
  REMETENTE VARCHAR2(200) NOT NULL,
  DESTINATARIO VARCHAR2(200) NOT NULL,
  ENDERECO_DESTINO VARCHAR2(500) NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'POSTADO' CHECK (STATUS IN ('POSTADO', 'EM_TRANSITO', 'ENTREGUE', 'DEVOLVIDO')),
  DATA_POSTAGEM DATE DEFAULT SYSDATE NOT NULL,
  DATA_ENTREGA DATE,
  VALOR_DECLARADO NUMBER(15,2),
  PESO NUMBER(10,3),
  OBSERVACOES CLOB,
  CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
  ATUALIZADO_EM DATE DEFAULT SYSDATE NOT NULL
);

-- Índices para ENCOMENDAS
CREATE INDEX IDX_ENCOMENDAS_CODIGO ON ENCOMENDAS(CODIGO_RASTREAMENTO);
CREATE INDEX IDX_ENCOMENDAS_STATUS ON ENCOMENDAS(STATUS);
CREATE INDEX IDX_ENCOMENDAS_REMETENTE ON ENCOMENDAS(UPPER(REMETENTE));
CREATE INDEX IDX_ENCOMENDAS_DESTINATARIO ON ENCOMENDAS(UPPER(DESTINATARIO));
CREATE INDEX IDX_ENCOMENDAS_DATA_POSTAGEM ON ENCOMENDAS(DATA_POSTAGEM);
CREATE INDEX IDX_ENCOMENDAS_DATA_ENTREGA ON ENCOMENDAS(DATA_ENTREGA);

-- =====================================================
-- TABELA: DOCUMENTOS
-- =====================================================
CREATE TABLE DOCUMENTOS (
  ID NUMBER(10) PRIMARY KEY,
  NOME VARCHAR2(255) NOT NULL,
  TIPO VARCHAR2(50) NOT NULL,
  EXTENSAO VARCHAR2(10) NOT NULL,
  TAMANHO NUMBER(15) NOT NULL,
  CATEGORIA VARCHAR2(100) NOT NULL,
  DESCRICAO CLOB,
  TAGS VARCHAR2(500),
  PASTA VARCHAR2(200) NOT NULL,
  NIVEL_ACESSO VARCHAR2(20) DEFAULT 'PUBLICO' CHECK (NIVEL_ACESSO IN ('PUBLICO', 'RESTRITO', 'CONFIDENCIAL')),
  DATA_UPLOAD DATE DEFAULT SYSDATE NOT NULL,
  DATA_MODIFICACAO DATE,
  UPLOADED_BY VARCHAR2(100) NOT NULL,
  MODIFICADO_POR VARCHAR2(100),
  URL VARCHAR2(500),
  VERSAO NUMBER(3) DEFAULT 1,
  STATUS VARCHAR2(20) DEFAULT 'ATIVO' CHECK (STATUS IN ('ATIVO', 'ARQUIVADO', 'EXCLUIDO')),
  CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
  ATUALIZADO_EM DATE DEFAULT SYSDATE NOT NULL
);

-- Índices para DOCUMENTOS
CREATE INDEX IDX_DOCUMENTOS_NOME ON DOCUMENTOS(UPPER(NOME));
CREATE INDEX IDX_DOCUMENTOS_TIPO ON DOCUMENTOS(UPPER(TIPO));
CREATE INDEX IDX_DOCUMENTOS_CATEGORIA ON DOCUMENTOS(UPPER(CATEGORIA));
CREATE INDEX IDX_DOCUMENTOS_PASTA ON DOCUMENTOS(UPPER(PASTA));
CREATE INDEX IDX_DOCUMENTOS_NIVEL_ACESSO ON DOCUMENTOS(NIVEL_ACESSO);
CREATE INDEX IDX_DOCUMENTOS_STATUS ON DOCUMENTOS(STATUS);
CREATE INDEX IDX_DOCUMENTOS_UPLOADED_BY ON DOCUMENTOS(UPPER(UPLOADED_BY));
CREATE INDEX IDX_DOCUMENTOS_DATA_UPLOAD ON DOCUMENTOS(DATA_UPLOAD);
CREATE INDEX IDX_DOCUMENTOS_TAGS ON DOCUMENTOS(UPPER(TAGS));

-- =====================================================
-- TABELA: PRAZOS
-- =====================================================
CREATE TABLE PRAZOS (
  ID NUMBER(10) PRIMARY KEY,
  TITULO VARCHAR2(200) NOT NULL,
  DESCRICAO CLOB NOT NULL,
  DATA_VENCIMENTO DATE NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'PENDENTE' CHECK (STATUS IN ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDO', 'VENCIDO')),
  PRIORIDADE VARCHAR2(20) DEFAULT 'MEDIA' CHECK (PRIORIDADE IN ('BAIXA', 'MEDIA', 'ALTA', 'URGENTE')),
  RESPONSAVEL VARCHAR2(100) NOT NULL,
  DATA_CONCLUSAO DATE,
  OBSERVACOES CLOB,
  CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
  ATUALIZADO_EM DATE DEFAULT SYSDATE NOT NULL
);

-- Índices para PRAZOS
CREATE INDEX IDX_PRAZOS_TITULO ON PRAZOS(UPPER(TITULO));
CREATE INDEX IDX_PRAZOS_STATUS ON PRAZOS(STATUS);
CREATE INDEX IDX_PRAZOS_PRIORIDADE ON PRAZOS(PRIORIDADE);
CREATE INDEX IDX_PRAZOS_RESPONSAVEL ON PRAZOS(UPPER(RESPONSAVEL));
CREATE INDEX IDX_PRAZOS_DATA_VENCIMENTO ON PRAZOS(DATA_VENCIMENTO);
CREATE INDEX IDX_PRAZOS_DATA_CONCLUSAO ON PRAZOS(DATA_CONCLUSAO);

-- =====================================================
-- TRIGGERS PARA AUTO INCREMENT
-- =====================================================

-- Trigger para ENCOMENDAS
CREATE OR REPLACE TRIGGER TRG_ENCOMENDAS_ID
  BEFORE INSERT ON ENCOMENDAS
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_ENCOMENDAS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
  :NEW.ATUALIZADO_EM := SYSDATE;
END;
/

-- Trigger para DOCUMENTOS
CREATE OR REPLACE TRIGGER TRG_DOCUMENTOS_ID
  BEFORE INSERT ON DOCUMENTOS
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_DOCUMENTOS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
  :NEW.ATUALIZADO_EM := SYSDATE;
END;
/

-- Trigger para PRAZOS
CREATE OR REPLACE TRIGGER TRG_PRAZOS_ID
  BEFORE INSERT ON PRAZOS
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_PRAZOS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
  :NEW.ATUALIZADO_EM := SYSDATE;
END;
/

-- Trigger para CONFIGURACOES
CREATE OR REPLACE TRIGGER TRG_CONFIGURACOES_ID
  BEFORE INSERT ON CONFIGURACOES
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_CONFIGURACOES.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
  :NEW.ATUALIZADO_EM := SYSDATE;
END;
/

-- =====================================================
-- TRIGGERS PARA UPDATE TIMESTAMP
-- =====================================================

-- Trigger para atualizar ATUALIZADO_EM em ENCOMENDAS
CREATE OR REPLACE TRIGGER TRG_ENCOMENDAS_UPDATE
  BEFORE UPDATE ON ENCOMENDAS
  FOR EACH ROW
BEGIN
  :NEW.ATUALIZADO_EM := SYSDATE;
END;
/

-- Trigger para atualizar ATUALIZADO_EM em DOCUMENTOS
CREATE OR REPLACE TRIGGER TRG_DOCUMENTOS_UPDATE
  BEFORE UPDATE ON DOCUMENTOS
  FOR EACH ROW
BEGIN
  :NEW.ATUALIZADO_EM := SYSDATE;
  :NEW.DATA_MODIFICACAO := SYSDATE;
END;
/

-- Trigger para atualizar ATUALIZADO_EM em PRAZOS
CREATE OR REPLACE TRIGGER TRG_PRAZOS_UPDATE
  BEFORE UPDATE ON PRAZOS
  FOR EACH ROW
BEGIN
  :NEW.ATUALIZADO_EM := SYSDATE;
  
  -- Atualizar status para VENCIDO se passou da data e ainda está pendente
  IF :NEW.DATA_VENCIMENTO < SYSDATE AND :NEW.STATUS = 'PENDENTE' THEN
    :NEW.STATUS := 'VENCIDO';
  END IF;
  
  -- Definir data de conclusão se status mudou para CONCLUIDO
  IF :NEW.STATUS = 'CONCLUIDO' AND :OLD.STATUS != 'CONCLUIDO' THEN
    :NEW.DATA_CONCLUSAO := SYSDATE;
  END IF;
END;
/

-- =====================================================
-- COMENTÁRIOS NAS TABELAS
-- =====================================================

COMMENT ON TABLE ENCOMENDAS IS 'Tabela de encomendas e rastreamento';
COMMENT ON TABLE DOCUMENTOS IS 'Tabela de documentos e arquivos';
COMMENT ON TABLE PRAZOS IS 'Tabela de prazos e vencimentos';

-- =====================================================
-- DADOS INICIAIS DE EXEMPLO
-- =====================================================

-- Inserir algumas configurações padrão se a tabela CONFIGURACOES existir
DECLARE
  table_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO table_exists
  FROM USER_TABLES
  WHERE TABLE_NAME = 'CONFIGURACOES';
  
  IF table_exists > 0 THEN
    -- Inserir configurações padrão
    INSERT INTO CONFIGURACOES (CHAVE, VALOR, DESCRICAO, CATEGORIA, TIPO_VALOR, ATIVO)
    SELECT 'SISTEMA_NOME', 'Sistema de Protocolo', 'Nome do sistema', 'SISTEMA', 'STRING', 'S' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM CONFIGURACOES WHERE CHAVE = 'SISTEMA_NOME');
    
    INSERT INTO CONFIGURACOES (CHAVE, VALOR, DESCRICAO, CATEGORIA, TIPO_VALOR, ATIVO)
    SELECT 'SISTEMA_VERSAO', '2.0.0', 'Versão do sistema', 'SISTEMA', 'STRING', 'S' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM CONFIGURACOES WHERE CHAVE = 'SISTEMA_VERSAO');
    
    INSERT INTO CONFIGURACOES (CHAVE, VALOR, DESCRICAO, CATEGORIA, TIPO_VALOR, ATIVO)
    SELECT 'MAX_UPLOAD_SIZE', '10485760', 'Tamanho máximo de upload em bytes (10MB)', 'UPLOAD', 'NUMBER', 'S' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM CONFIGURACOES WHERE CHAVE = 'MAX_UPLOAD_SIZE');
    
    DBMS_OUTPUT.PUT_LINE('Configurações padrão inseridas.');
  END IF;
END;
/

-- =====================================================
-- FINALIZAÇÃO
-- =====================================================

PROMPT 'Tabelas faltantes criadas com sucesso!';
PROMPT 'Tabelas criadas: ENCOMENDAS, DOCUMENTOS, PRAZOS';
PROMPT 'Sequências e triggers configurados.';
PROMPT 'Execute o backend para testar as novas funcionalidades.';

COMMIT;