-- Adicionar campos CODIGO_LACRE_MALOTE e QR_CODE à tabela ENCOMENDAS
ALTER TABLE ENCOMENDAS ADD CODIGO_LACRE_MALOTE VARCHAR2(50);
ALTER TABLE ENCOMENDAS ADD QR_CODE CLOB;

-- Verificar se os campos foram adicionados
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'ENCOMENDAS' 
ORDER BY COLUMN_ID;