-- Adicionar campo CODIGO_BARRAS à tabela ENCOMENDAS
ALTER TABLE ENCOMENDAS ADD CODIGO_BARRAS VARCHAR2(100);

-- Verificar se o campo foi adicionado
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'ENCOMENDAS' 
AND COLUMN_NAME = 'CODIGO_BARRAS'
ORDER BY COLUMN_ID;