-- Script para debug do status dos malotes
-- Verifica o status real dos malotes e suas encomendas vinculadas

PROMPT === Verificando status dos malotes e encomendas vinculadas ===;

SELECT 
  m.ID AS MALOTE_ID,
  m.NUMERO_MALOTE,
  m.SETOR_ORIGEM_ID,
  m.SETOR_DESTINO_ID,
  m.STATUS AS MALOTE_STATUS,
  m.ENCOMENDA_ID,
  e.ID AS ENCOMENDA_ID_REAL,
  e.NUMERO_ENCOMENDA,
  e.STATUS AS ENCOMENDA_STATUS,
  e.SETOR_ORIGEM_ID AS ENC_SETOR_ORIGEM,
  e.SETOR_DESTINO_ID AS ENC_SETOR_DESTINO,
  CASE 
    WHEN e.ID IS NOT NULL AND (
      UPPER(REPLACE(TRIM(e.STATUS), ' ', '_')) IN ('EM_TRANSITO','EM_TRÂNSITO','EMTRANSITO','EM TRANSITO','EM TRÂNSITO')
      OR UPPER(TRIM(e.STATUS)) IN ('POSTADO','TRANSITO','TRÂNSITO')
    ) THEN 'INDISPONIVEL - EM TRANSITO'
    WHEN e.ID IS NOT NULL AND UPPER(TRIM(e.STATUS)) = 'ENTREGUE' THEN 'DISPONIVEL - ENTREGUE'
    WHEN e.ID IS NULL THEN 'DISPONIVEL - SEM ENCOMENDA'
    ELSE 'OUTRO STATUS: ' || e.STATUS
  END AS STATUS_CALCULADO
FROM MALOTE m
LEFT JOIN ENCOMENDAS e ON e.MALOTE_ID = m.ID
WHERE m.NUMERO_MALOTE IN ('00037', '00038', '00039', '00040')
ORDER BY m.NUMERO_MALOTE;

PROMPT === Verificando encomendas com status em_transito ===;

SELECT 
  e.ID,
  e.NUMERO_ENCOMENDA,
  e.STATUS,
  e.MALOTE_ID,
  e.SETOR_ORIGEM_ID,
  e.SETOR_DESTINO_ID,
  m.NUMERO_MALOTE,
  m.STATUS AS MALOTE_STATUS
FROM ENCOMENDAS e
LEFT JOIN MALOTE m ON m.ID = e.MALOTE_ID
WHERE UPPER(REPLACE(TRIM(e.STATUS), ' ', '_')) IN ('EM_TRANSITO','EM_TRÂNSITO','EMTRANSITO','EM TRANSITO','EM TRÂNSITO')
   OR UPPER(TRIM(e.STATUS)) IN ('POSTADO','TRANSITO','TRÂNSITO')
ORDER BY e.ID DESC
FETCH FIRST 20 ROWS ONLY;

PROMPT === Verificando malotes do setor 172 (Delegacia Regional de Fiscalização - Taguatinga) ===;

SELECT 
  m.ID AS MALOTE_ID,
  m.NUMERO_MALOTE,
  m.SETOR_ORIGEM_ID,
  m.SETOR_DESTINO_ID,
  m.STATUS AS MALOTE_STATUS,
  m.ENCOMENDA_ID,
  e.STATUS AS ENCOMENDA_STATUS,
  CASE 
    WHEN EXISTS (
      SELECT 1 FROM ENCOMENDAS e2
      WHERE e2.MALOTE_ID = m.ID
        AND (
          UPPER(REPLACE(TRIM(e2.STATUS), ' ', '_')) IN ('EM_TRANSITO','EM_TRÂNSITO','EMTRANSITO','EM TRANSITO','EM TRÂNSITO')
          OR UPPER(TRIM(e2.STATUS)) IN ('POSTADO','TRANSITO','TRÂNSITO')
        )
    ) THEN 'INDISPONIVEL'
    ELSE 'DISPONIVEL'
  END AS STATUS_CALCULADO
FROM MALOTE m
LEFT JOIN ENCOMENDAS e ON e.MALOTE_ID = m.ID
WHERE m.SETOR_DESTINO_ID = 172 OR m.SETOR_ORIGEM_ID = 172
ORDER BY m.NUMERO_MALOTE;
