-- Script para corrigir relacionamentos da tabela SETORES
-- Adicionar colunas necessárias nas tabelas USUARIOS e ENCOMENDAS

-- Adicionar colunas organizacionais na tabela USUARIOS
ALTER TABLE USUARIOS ADD (
  SETOR_ID NUMBER,
  ORGAO VARCHAR2(200),
  SETOR VARCHAR2(200),
  LOTACAO VARCHAR2(200)
);

-- Adicionar colunas de setores na tabela ENCOMENDAS
ALTER TABLE ENCOMENDAS ADD (
  SETOR_ORIGEM_ID NUMBER,
  SETOR_DESTINO_ID NUMBER
);

-- Criar índices para melhor performance
CREATE INDEX IDX_USUARIOS_SETOR_ID ON USUARIOS(SETOR_ID);
CREATE INDEX IDX_ENCOMENDAS_SETOR_ORIGEM ON ENCOMENDAS(SETOR_ORIGEM_ID);
CREATE INDEX IDX_ENCOMENDAS_SETOR_DESTINO ON ENCOMENDAS(SETOR_DESTINO_ID);

-- Criar chaves estrangeiras
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_SETOR 
  FOREIGN KEY (SETOR_ID) REFERENCES SETORES(ID);

ALTER TABLE ENCOMENDAS ADD CONSTRAINT FK_ENCOMENDAS_SETOR_ORIGEM 
  FOREIGN KEY (SETOR_ORIGEM_ID) REFERENCES SETORES(ID);

ALTER TABLE ENCOMENDAS ADD CONSTRAINT FK_ENCOMENDAS_SETOR_DESTINO 
  FOREIGN KEY (SETOR_DESTINO_ID) REFERENCES SETORES(ID);

-- Popular tabela SETORES com alguns dados básicos
INSERT INTO SETORES (ID, CODIGO_SETOR, ORGAO, SETOR, LOTACAO, ATIVO, CREATED_AT) VALUES 
(1, 'SEFAZ-001', 'SEFAZ', 'SECRETARIA DA FAZENDA', 'SEDE', 1, CURRENT_TIMESTAMP);

INSERT INTO SETORES (ID, CODIGO_SETOR, ORGAO, SETOR, LOTACAO, ATIVO, CREATED_AT) VALUES 
(2, 'SEFAZ-002', 'SEFAZ', 'DIRETORIA DE ADMINISTRAÇÃO', 'SEDE', 1, CURRENT_TIMESTAMP);

INSERT INTO SETORES (ID, CODIGO_SETOR, ORGAO, SETOR, LOTACAO, ATIVO, CREATED_AT) VALUES 
(3, 'SEFAZ-003', 'SEFAZ', 'DIRETORIA DE ARRECADAÇÃO', 'SEDE', 1, CURRENT_TIMESTAMP);

COMMIT;

SELECT 'Relacionamentos da tabela SETORES criados com sucesso!' AS resultado FROM DUAL;