-- Script simplificado para corrigir relacionamentos
-- Executar comando por comando

-- 1. Adicionar coluna TIPO_PROCESSO_ID na tabela PROCESSOS
ALTER TABLE PROCESSOS ADD TIPO_PROCESSO_ID NUMBER(10);

-- 2. Criar foreign key entre PROCESSOS e TIPOS_PROCESSO
ALTER TABLE PROCESSOS ADD CONSTRAINT FK_PROCESSOS_TIPO_PROCESSO 
FOREIGN KEY (TIPO_PROCESSO_ID) REFERENCES TIPOS_PROCESSO(ID);

-- 3. Criar índice para LOGS_AUDITORIA
CREATE INDEX IDX_LOGS_TABELA_REGISTRO ON LOGS_AUDITORIA(TABELA, REGISTRO_ID);

-- 4. Criar view MOVIMENTACOES
CREATE OR REPLACE VIEW MOVIMENTACOES AS
SELECT 
    ID,
    PROCESSO_ID,
    SETOR_ORIGEM,
    SETOR_DESTINO,
    USUARIO_ORIGEM_ID,
    USUARIO_DESTINO_ID,
    DATA_TRAMITACAO AS DATA_MOVIMENTACAO,
    DATA_RECEBIMENTO,
    OBSERVACOES,
    TIPO_TRAMITACAO AS TIPO_MOVIMENTACAO,
    STATUS,
    PRAZO_RESPOSTA,
    URGENTE,
    CRIADO_EM
FROM TRAMITACOES;

-- 5. Criar índices para PROCESSOS
CREATE INDEX IDX_PROCESSOS_SETOR_ORIGEM ON PROCESSOS(SETOR_ORIGEM);
CREATE INDEX IDX_PROCESSOS_SETOR_ATUAL ON PROCESSOS(SETOR_ATUAL);

COMMIT;