-- Script para reestruturação da tabela USUARIOS
-- Banco: FREEPDB1
-- Schema: protocolo_user
-- Data: 2024

-- Conectar como protocolo_user
-- CONNECT protocolo_user/Anderline49@localhost:1521/FREEPDB1;

-- 1. Fazer backup da tabela atual (opcional)
CREATE TABLE USUARIOS_BACKUP AS SELECT * FROM USUARIOS;

-- 2. Dropar a tabela atual (cuidado - fazer backup antes!)
-- DROP TABLE USUARIOS CASCADE CONSTRAINTS;

-- 3. Criar nova estrutura da tabela USUARIOS
CREATE TABLE USUARIOS (
    -- Campos principais
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SETOR_ID NUMBER,
    ROLE VARCHAR2(10) DEFAULT 'USER' CHECK (ROLE IN ('ADMIN', 'USER')),
    SENHA VARCHAR2(255), -- Para armazenar hash da senha
    TENTATIVAS_LOGIN NUMBER DEFAULT 0,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BLOQUEADO_ATE TIMESTAMP,
    
    -- Dados pessoais básicos
    NOME VARCHAR2(255) NOT NULL,
    MATRICULA NUMBER,
    VINCULO_FUNCIONAL NUMBER(2), -- Máximo 2-4 caracteres conforme solicitado
    CPF NUMBER(11),
    PIS_PASEP NUMBER(11),
    SEXO CHAR(1) CHECK (SEXO IN ('M', 'F')),
    ESTADO_CIVIL VARCHAR2(50),
    DATA_NASCIMENTO DATE,
    PAI VARCHAR2(255),
    MAE VARCHAR2(255),
    
    -- Documentos
    RG VARCHAR2(20),
    TIPO_RG VARCHAR2(50),
    ORGAO_EXPEDITOR VARCHAR2(50),
    UF_RG VARCHAR2(2),
    EXPEDICAO_RG DATE,
    CIDADE_NASCIMENTO VARCHAR2(100),
    UF_NASCIMENTO VARCHAR2(2),
    
    -- Características pessoais
    TIPO_SANGUINEO VARCHAR2(5),
    RACA_COR VARCHAR2(50),
    PNE VARCHAR2(100), -- Pessoa com Necessidades Especiais
    
    -- Dados funcionais
    TIPO_VINCULO VARCHAR2(100),
    CATEGORIA VARCHAR2(100),
    REGIME_JURIDICO VARCHAR2(100),
    REGIME_PREVIDENCIARIO VARCHAR2(100),
    EVENTO_TIPO VARCHAR2(100),
    FORMA_PROVIMENTO VARCHAR2(100),
    CODIGO_CARGO VARCHAR2(20),
    CARGO VARCHAR2(255),
    ESCOLARIDADE_CARGO VARCHAR2(100),
    ESCOLARIDADE_SERVIDOR VARCHAR2(100),
    FORMACAO_PROFISSIONAL_1 VARCHAR2(255),
    FORMACAO_PROFISSIONAL_2 VARCHAR2(255),
    JORNADA VARCHAR2(50),
    NIVEL_REFERENCIA VARCHAR2(50),
    COMISSAO_FUNCAO VARCHAR2(255),
    DATA_INI_COMISSAO DATE,
    
    -- Contato
    TELEFONE VARCHAR2(20),
    
    -- Endereço
    ENDERECO VARCHAR2(255),
    NUMERO_ENDERECO VARCHAR2(10),
    COMPLEMENTO_ENDERECO VARCHAR2(100),
    BAIRRO_ENDERECO VARCHAR2(100),
    CIDADE_ENDERECO VARCHAR2(100),
    UF_ENDERECO VARCHAR2(2),
    CEP_ENDERECO VARCHAR2(10),
    
    -- Email
    E_MAIL VARCHAR2(255) NOT NULL UNIQUE,
    
    -- Campos de controle (compatibilidade)
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    
    -- Constraint de chave estrangeira para SETORES
    CONSTRAINT FK_USUARIOS_SETOR FOREIGN KEY (SETOR_ID) REFERENCES SETORES(ID)
);

-- 4. Criar índices para melhor performance
CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(E_MAIL);
CREATE INDEX IDX_USUARIOS_CPF ON USUARIOS(CPF);
CREATE INDEX IDX_USUARIOS_MATRICULA ON USUARIOS(MATRICULA);
CREATE INDEX IDX_USUARIOS_SETOR_ID ON USUARIOS(SETOR_ID);
CREATE INDEX IDX_USUARIOS_ROLE ON USUARIOS(ROLE);
CREATE INDEX IDX_USUARIOS_ATIVO ON USUARIOS(IS_ACTIVE);

-- 5. Criar trigger para atualizar DATA_ATUALIZACAO automaticamente
CREATE OR REPLACE TRIGGER TRG_USUARIOS_UPDATE_DATE
    BEFORE UPDATE ON USUARIOS
    FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- 6. Criar sequência para MATRICULA (se necessário)
CREATE SEQUENCE SEQ_MATRICULA
    START WITH 100001
    INCREMENT BY 1
    NOCACHE;

-- 7. Inserir usuário administrador padrão com senha padrão
-- Senha padrão: Admin@123 (atende aos critérios: 8 caracteres, 1 maiúscula, 1 especial)
INSERT INTO USUARIOS (
    NOME, 
    E_MAIL, 
    SENHA, 
    ROLE, 
    MATRICULA,
    SETOR_ID,
    IS_ACTIVE,
    VINCULO_FUNCIONAL
) VALUES (
    'Administrador do Sistema',
    'admin_protocolo@sefaz.to.gov.br',
    '$2b$12$LQv3c1yqBwEHXw.9oC9FEO4SdHWw5uIUuIWxFJxeoJxs2xe4Rb3Oi', -- Hash de 'Admin@123'
    'ADMIN',
    100001,
    1, -- Assumindo que existe setor com ID 1
    1,
    01
);

-- 8. Inserir alguns usuários de exemplo com senha padrão
-- Senha padrão para todos: User@123
INSERT INTO USUARIOS (
    NOME, 
    E_MAIL, 
    SENHA, 
    ROLE, 
    MATRICULA,
    SETOR_ID,
    IS_ACTIVE,
    VINCULO_FUNCIONAL,
    CPF,
    TELEFONE,
    SEXO
) VALUES 
(
    'João Silva Santos',
    'joao.silva@sefaz.to.gov.br',
    '$2b$12$8Ry9YjLg5tFhGxCvBnKrHOGGq4vN2Qx3Zw8Kp7Lm9Nq5Rs6Tv7Uw', -- Hash de 'User@123'
    'USER',
    100002,
    1,
    1,
    01,
    12345678901,
    '(63) 99999-1234',
    'M'
),
(
    'Maria Oliveira Costa',
    'maria.oliveira@sefaz.to.gov.br',
    '$2b$12$8Ry9YjLg5tFhGxCvBnKrHOGGq4vN2Qx3Zw8Kp7Lm9Nq5Rs6Tv7Uw', -- Hash de 'User@123'
    'USER',
    100003,
    1,
    1,
    01,
    98765432109,
    '(63) 99999-5678',
    'F'
);

-- 9. Criar view para compatibilidade com código existente (se necessário)
CREATE OR REPLACE VIEW VW_USUARIOS_COMPATIBILIDADE AS
SELECT 
    ID,
    NOME AS NAME,
    E_MAIL AS EMAIL,
    SENHA AS PASSWORD_HASH,
    ROLE,
    TELEFONE AS PHONE,
    IS_ACTIVE,
    SETOR_ID,
    MATRICULA,
    VINCULO_FUNCIONAL,
    CREATED_AT,
    UPDATED_AT,
    LAST_LOGIN,
    CPF,
    CARGO
FROM USUARIOS;

-- 10. Comentários nas colunas para documentação
COMMENT ON TABLE USUARIOS IS 'Tabela de usuários do sistema de protocolo - Reestruturada em 2024';
COMMENT ON COLUMN USUARIOS.ID IS 'Identificador único do usuário';
COMMENT ON COLUMN USUARIOS.SETOR_ID IS 'Referência ao setor do usuário (FK para SETORES)';
COMMENT ON COLUMN USUARIOS.ROLE IS 'Perfil do usuário: ADMIN ou USER';
COMMENT ON COLUMN USUARIOS.SENHA IS 'Hash da senha do usuário (máximo 8 caracteres originais)';
COMMENT ON COLUMN USUARIOS.TENTATIVAS_LOGIN IS 'Contador de tentativas de login falhadas';
COMMENT ON COLUMN USUARIOS.BLOQUEADO_ATE IS 'Data/hora até quando o usuário está bloqueado';
COMMENT ON COLUMN USUARIOS.VINCULO_FUNCIONAL IS 'Código do vínculo funcional (2-4 dígitos)';
COMMENT ON COLUMN USUARIOS.E_MAIL IS 'Email principal do usuário (único)';

-- 11. Grants necessários (ajustar conforme necessário)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIOS TO protocolo_app;
-- GRANT SELECT ON VW_USUARIOS_COMPATIBILIDADE TO protocolo_app;

COMMIT;

-- Verificar a estrutura criada
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS'
ORDER BY COLUMN_ID;

-- Verificar dados inseridos
SELECT ID, NOME, E_MAIL, ROLE, MATRICULA, IS_ACTIVE 
FROM USUARIOS;