-- =====================================================
-- Script: Reestruturação da Tabela USUARIOS
-- Descrição: Reorganiza a tabela USUARIOS com a ordem exata de colunas especificada
-- Data: 14/10/2025
-- Autor: Sistema de Protocolo
-- =====================================================

-- Conectar ao banco de dados
CONNECT protocolo_user/Anderline49@localhost:1521/FREEPDB1;

-- Definir formato de data
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

-- Fazer backup dos dados existentes
CREATE TABLE USUARIOS_BACKUP_ORDEM AS SELECT * FROM USUARIOS;

-- Dropar a tabela atual
DROP TABLE USUARIOS CASCADE CONSTRAINTS;

-- Criar a nova tabela com a ordem exata especificada
CREATE TABLE USUARIOS (
    ID NUMBER(10) NOT NULL,
    SETOR_ID NUMBER(10),
    ROLE VARCHAR2(50) DEFAULT 'user' NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    USUARIO_ATIVO NUMBER(1) DEFAULT 1 NOT NULL,
    ULTIMO_LOGIN DATE,
    TENTATIVAS_LOGIN NUMBER(3) DEFAULT 0,
    DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL,
    DATA_ATUALIZACAO DATE DEFAULT SYSDATE NOT NULL,
    BLOQUEADO_ATE DATE,
    NOME VARCHAR2(255) NOT NULL,
    MATRICULA VARCHAR2(50),
    VINCULO_FUNCIONAL VARCHAR2(100),
    CPF VARCHAR2(14),
    "PIS/PASEP" VARCHAR2(20),
    SEXO VARCHAR2(1),
    ESTADO_CIVIL VARCHAR2(20),
    DATA_NASCIMENTO DATE,
    PAI VARCHAR2(255),
    MAE VARCHAR2(255),
    RG VARCHAR2(20),
    TIPO_RG VARCHAR2(50),
    ORGAO_EXPEDITOR VARCHAR2(100),
    UF_RG VARCHAR2(2),
    EXPEDICAO_RG DATE,
    CIDADE_NASCIMENTO VARCHAR2(100),
    UF_NASCIMENTO VARCHAR2(2),
    TIPO_SANGUINEO VARCHAR2(5),
    RACA_COR VARCHAR2(50),
    PNE NUMBER(1) DEFAULT 0,
    TIPO_VINCULO VARCHAR2(100),
    CATEGORIA VARCHAR2(100),
    REGIME_JURIDICO VARCHAR2(100),
    REGIME_PREVIDENCIARIO VARCHAR2(100),
    EVENTO_TIPO VARCHAR2(100),
    FORMA_PROVIMENTO VARCHAR2(100),
    CODIGO_CARGO VARCHAR2(20),
    CARGO VARCHAR2(255),
    ESCOLARIDADE_CARGO VARCHAR2(100),
    ESCOLARIDADE_SERVIDOR VARCHAR2(100),
    FORMACAO_PROFISSIONAL_1 VARCHAR2(255),
    FORMACAO_PROFISSIONAL_2 VARCHAR2(255),
    JORNADA VARCHAR2(50),
    NIVEL_REFERENCIA VARCHAR2(50),
    "COMISSAO_FUNÇAO" VARCHAR2(255),
    DATA_INI_COMISSAO DATE,
    TELEFONE VARCHAR2(20),
    ENDERECO VARCHAR2(255),
    NUMERO_ENDERECO VARCHAR2(20),
    COMPLEMENTO_ENDERECO VARCHAR2(100),
    BAIRRO_ENDERECO VARCHAR2(100),
    CIDADE_ENDERECO VARCHAR2(100),
    UF_ENDERECO VARCHAR2(2),
    CEP_ENDERECO VARCHAR2(10),
    E_MAIL VARCHAR2(255)
);

-- Adicionar comentários às colunas
COMMENT ON TABLE USUARIOS IS 'Tabela de usuários do sistema de protocolo - estrutura reorganizada';
COMMENT ON COLUMN USUARIOS.ID IS 'Identificador único do usuário';
COMMENT ON COLUMN USUARIOS.SETOR_ID IS 'Referência ao setor do usuário';
COMMENT ON COLUMN USUARIOS.ROLE IS 'Perfil/função do usuário no sistema';
COMMENT ON COLUMN USUARIOS.SENHA IS 'Senha criptografada do usuário';
COMMENT ON COLUMN USUARIOS.USUARIO_ATIVO IS 'Status ativo do usuário (1=ativo, 0=inativo)';
COMMENT ON COLUMN USUARIOS.ULTIMO_LOGIN IS 'Data e hora do último login';
COMMENT ON COLUMN USUARIOS.TENTATIVAS_LOGIN IS 'Número de tentativas de login falhadas';
COMMENT ON COLUMN USUARIOS.DATA_CRIACAO IS 'Data de criação do registro';
COMMENT ON COLUMN USUARIOS.DATA_ATUALIZACAO IS 'Data da última atualização';
COMMENT ON COLUMN USUARIOS.BLOQUEADO_ATE IS 'Data até quando o usuário está bloqueado';
COMMENT ON COLUMN USUARIOS.NOME IS 'Nome completo do usuário';
COMMENT ON COLUMN USUARIOS.MATRICULA IS 'Matrícula funcional';
COMMENT ON COLUMN USUARIOS.VINCULO_FUNCIONAL IS 'Tipo de vínculo funcional';
COMMENT ON COLUMN USUARIOS.CPF IS 'Cadastro de Pessoa Física';
COMMENT ON COLUMN USUARIOS."PIS/PASEP" IS 'Número do PIS/PASEP';
COMMENT ON COLUMN USUARIOS.SEXO IS 'Sexo (M/F)';
COMMENT ON COLUMN USUARIOS.ESTADO_CIVIL IS 'Estado civil';
COMMENT ON COLUMN USUARIOS.DATA_NASCIMENTO IS 'Data de nascimento';
COMMENT ON COLUMN USUARIOS.PAI IS 'Nome do pai';
COMMENT ON COLUMN USUARIOS.MAE IS 'Nome da mãe';
COMMENT ON COLUMN USUARIOS.RG IS 'Registro Geral';
COMMENT ON COLUMN USUARIOS.TIPO_RG IS 'Tipo do documento de identidade';
COMMENT ON COLUMN USUARIOS.ORGAO_EXPEDITOR IS 'Órgão expedidor do RG';
COMMENT ON COLUMN USUARIOS.UF_RG IS 'UF do órgão expedidor';
COMMENT ON COLUMN USUARIOS.EXPEDICAO_RG IS 'Data de expedição do RG';
COMMENT ON COLUMN USUARIOS.CIDADE_NASCIMENTO IS 'Cidade de nascimento';
COMMENT ON COLUMN USUARIOS.UF_NASCIMENTO IS 'UF de nascimento';
COMMENT ON COLUMN USUARIOS.TIPO_SANGUINEO IS 'Tipo sanguíneo';
COMMENT ON COLUMN USUARIOS.RACA_COR IS 'Raça/cor';
COMMENT ON COLUMN USUARIOS.PNE IS 'Pessoa com necessidades especiais (1=sim, 0=não)';
COMMENT ON COLUMN USUARIOS.TIPO_VINCULO IS 'Tipo de vínculo empregatício';
COMMENT ON COLUMN USUARIOS.CATEGORIA IS 'Categoria funcional';
COMMENT ON COLUMN USUARIOS.REGIME_JURIDICO IS 'Regime jurídico';
COMMENT ON COLUMN USUARIOS.REGIME_PREVIDENCIARIO IS 'Regime previdenciário';
COMMENT ON COLUMN USUARIOS.EVENTO_TIPO IS 'Tipo de evento';
COMMENT ON COLUMN USUARIOS.FORMA_PROVIMENTO IS 'Forma de provimento';
COMMENT ON COLUMN USUARIOS.CODIGO_CARGO IS 'Código do cargo';
COMMENT ON COLUMN USUARIOS.CARGO IS 'Descrição do cargo';
COMMENT ON COLUMN USUARIOS.ESCOLARIDADE_CARGO IS 'Escolaridade exigida para o cargo';
COMMENT ON COLUMN USUARIOS.ESCOLARIDADE_SERVIDOR IS 'Escolaridade do servidor';
COMMENT ON COLUMN USUARIOS.FORMACAO_PROFISSIONAL_1 IS 'Primeira formação profissional';
COMMENT ON COLUMN USUARIOS.FORMACAO_PROFISSIONAL_2 IS 'Segunda formação profissional';
COMMENT ON COLUMN USUARIOS.JORNADA IS 'Jornada de trabalho';
COMMENT ON COLUMN USUARIOS.NIVEL_REFERENCIA IS 'Nível de referência';
COMMENT ON COLUMN USUARIOS."COMISSAO_FUNÇAO" IS 'Comissão ou função';
COMMENT ON COLUMN USUARIOS.DATA_INI_COMISSAO IS 'Data de início da comissão';
COMMENT ON COLUMN USUARIOS.TELEFONE IS 'Telefone de contato';
COMMENT ON COLUMN USUARIOS.ENDERECO IS 'Endereço residencial';
COMMENT ON COLUMN USUARIOS.NUMERO_ENDERECO IS 'Número do endereço';
COMMENT ON COLUMN USUARIOS.COMPLEMENTO_ENDERECO IS 'Complemento do endereço';
COMMENT ON COLUMN USUARIOS.BAIRRO_ENDERECO IS 'Bairro';
COMMENT ON COLUMN USUARIOS.CIDADE_ENDERECO IS 'Cidade';
COMMENT ON COLUMN USUARIOS.UF_ENDERECO IS 'UF do endereço';
COMMENT ON COLUMN USUARIOS.CEP_ENDERECO IS 'CEP';
COMMENT ON COLUMN USUARIOS.E_MAIL IS 'Email do usuário';

-- Criar chave primária
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (ID);

-- Criar índices
CREATE INDEX IDX_USUARIOS_SETOR ON USUARIOS (SETOR_ID);
CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS (E_MAIL);
CREATE INDEX IDX_USUARIOS_CPF ON USUARIOS (CPF);
CREATE INDEX IDX_USUARIOS_MATRICULA ON USUARIOS (MATRICULA);
CREATE INDEX IDX_USUARIOS_ATIVO ON USUARIOS (USUARIO_ATIVO);
CREATE INDEX IDX_USUARIOS_ROLE ON USUARIOS (ROLE);

-- Criar constraints de verificação
ALTER TABLE USUARIOS ADD CONSTRAINT CHK_USUARIOS_ATIVO CHECK (USUARIO_ATIVO IN (0, 1));
ALTER TABLE USUARIOS ADD CONSTRAINT CHK_USUARIOS_SEXO CHECK (SEXO IN ('M', 'F'));
ALTER TABLE USUARIOS ADD CONSTRAINT CHK_USUARIOS_PNE CHECK (PNE IN (0, 1));
ALTER TABLE USUARIOS ADD CONSTRAINT CHK_USUARIOS_TENTATIVAS CHECK (TENTATIVAS_LOGIN >= 0);

-- Criar constraint de email único
ALTER TABLE USUARIOS ADD CONSTRAINT UK_USUARIOS_EMAIL UNIQUE (E_MAIL);

-- Criar sequence para ID
CREATE SEQUENCE SEQ_USUARIOS_ID START WITH 1 INCREMENT BY 1;

-- Criar trigger para atualização automática de DATA_ATUALIZACAO
CREATE OR REPLACE TRIGGER TRG_USUARIOS_UPDATE
    BEFORE UPDATE ON USUARIOS
    FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := SYSDATE;
END;
/

-- Migrar dados do backup para a nova estrutura
INSERT INTO USUARIOS (
    ID, SETOR_ID, ROLE, SENHA, USUARIO_ATIVO, ULTIMO_LOGIN, TENTATIVAS_LOGIN,
    DATA_CRIACAO, DATA_ATUALIZACAO, BLOQUEADO_ATE, NOME, MATRICULA, VINCULO_FUNCIONAL,
    CPF, "PIS/PASEP", SEXO, ESTADO_CIVIL, DATA_NASCIMENTO, PAI, MAE, RG, TIPO_RG,
    ORGAO_EXPEDITOR, UF_RG, EXPEDICAO_RG, CIDADE_NASCIMENTO, UF_NASCIMENTO,
    TIPO_SANGUINEO, RACA_COR, PNE, TIPO_VINCULO, CATEGORIA, REGIME_JURIDICO,
    REGIME_PREVIDENCIARIO, EVENTO_TIPO, FORMA_PROVIMENTO, CODIGO_CARGO, CARGO,
    ESCOLARIDADE_CARGO, ESCOLARIDADE_SERVIDOR, FORMACAO_PROFISSIONAL_1,
    FORMACAO_PROFISSIONAL_2, JORNADA, NIVEL_REFERENCIA, "COMISSAO_FUNÇAO",
    DATA_INI_COMISSAO, TELEFONE, ENDERECO, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO,
    BAIRRO_ENDERECO, CIDADE_ENDERECO, UF_ENDERECO, CEP_ENDERECO, E_MAIL
)
SELECT 
    ID, SETOR_ID, ROLE, SENHA, USUARIO_ATIVO, ULTIMO_LOGIN, TENTATIVAS_LOGIN,
    CREATED_AT, UPDATED_AT, BLOQUEADO_ATE, NOME, MATRICULA, VINCULO_FUNCIONAL,
    CPF, PIS_PASEP, SEXO, ESTADO_CIVIL, DATA_NASCIMENTO, PAI, MAE, RG, TIPO_RG,
    ORGAO_EXPEDITOR, UF_RG, EXPEDICAO_RG, CIDADE_NASCIMENTO, UF_NASCIMENTO,
    TIPO_SANGUINEO, RACA_COR, PNE, TIPO_VINCULO, CATEGORIA, REGIME_JURIDICO,
    REGIME_PREVIDENCIARIO, EVENTO_TIPO, FORMA_PROVIMENTO, CODIGO_CARGO, CARGO,
    ESCOLARIDADE_CARGO, ESCOLARIDADE_SERVIDOR, FORMACAO_PROFISSIONAL_1,
    FORMACAO_PROFISSIONAL_2, JORNADA, NIVEL_REFERENCIA, COMISSAO_FUNCAO,
    DATA_INI_COMISSAO, TELEFONE, ENDERECO, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO,
    BAIRRO_ENDERECO, CIDADE_ENDERECO, UF_ENDERECO, CEP_ENDERECO, EMAIL
FROM USUARIOS_BACKUP_ORDEM;

-- Verificar migração
SELECT COUNT(*) AS "Total de usuários migrados" FROM USUARIOS;

-- Mostrar estrutura da tabela
DESCRIBE USUARIOS;

-- Commit das alterações
COMMIT;

PROMPT 'Reestruturação da tabela USUARIOS concluída com sucesso!';
PROMPT 'Estrutura reorganizada com a ordem exata de colunas especificada.';
PROMPT 'DATA_CRIACAO e DATA_ATUALIZACAO substituem CREATED_AT e UPDATED_AT.';