-- =====================================================
-- SCRIPT: Verificar Estrutura Atual da Tabela USUARIOS
-- DATA: 14/10/2025
-- DESCRIÇÃO: Verifica a estrutura atual da tabela antes
--           de executar a reestruturação
-- =====================================================

-- 1. VERIFICAR SE A TABELA EXISTE
SELECT 'Tabela USUARIOS existe' AS STATUS 
FROM USER_TABLES 
WHERE TABLE_NAME = 'USUARIOS';

-- 2. VERIFICAR ESTRUTURA ATUAL
SELECT 
    COLUMN_ID AS POSICAO,
    COLUMN_NAME AS COLUNA,
    DATA_TYPE AS TIPO,
    DATA_LENGTH AS TAMANHO,
    NULLABLE AS PERMITE_NULL,
    DATA_DEFAULT AS VALOR_PADRAO
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS'
ORDER BY COLUMN_ID;

-- 3. CONTAR REGISTROS EXISTENTES
SELECT COUNT(*) AS TOTAL_REGISTROS FROM USUARIOS;

-- 4. VERIFICAR CONSTRAINTS
SELECT 
    CONSTRAINT_NAME AS NOME_CONSTRAINT,
    CONSTRAINT_TYPE AS TIPO,
    SEARCH_CONDITION AS CONDICAO
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'USUARIOS';

-- 5. VERIFICAR ÍNDICES
SELECT 
    INDEX_NAME AS NOME_INDICE,
    COLUMN_NAME AS COLUNA,
    COLUMN_POSITION AS POSICAO
FROM USER_IND_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS'
ORDER BY INDEX_NAME, COLUMN_POSITION;

-- 6. VERIFICAR FOREIGN KEYS
SELECT 
    a.CONSTRAINT_NAME AS FK_NAME,
    a.COLUMN_NAME AS COLUNA_LOCAL,
    c_pk.TABLE_NAME AS TABELA_REFERENCIADA,
    b.COLUMN_NAME AS COLUNA_REFERENCIADA
FROM USER_CONS_COLUMNS a
JOIN USER_CONSTRAINTS c ON a.CONSTRAINT_NAME = c.CONSTRAINT_NAME
JOIN USER_CONSTRAINTS c_pk ON c.R_CONSTRAINT_NAME = c_pk.CONSTRAINT_NAME
JOIN USER_CONS_COLUMNS b ON c_pk.CONSTRAINT_NAME = b.CONSTRAINT_NAME
WHERE c.CONSTRAINT_TYPE = 'R'
AND a.TABLE_NAME = 'USUARIOS';

-- 7. VERIFICAR TRIGGERS
SELECT 
    TRIGGER_NAME AS NOME_TRIGGER,
    TRIGGERING_EVENT AS EVENTO,
    STATUS
FROM USER_TRIGGERS 
WHERE TABLE_NAME = 'USUARIOS';

-- 8. AMOSTRA DOS DADOS (PRIMEIROS 5 REGISTROS)
SELECT * FROM (
    SELECT 
        ID,
        SETOR_ID,
        NOME,
        E_MAIL,
        ROLE,
        USUARIO_ATIVO,
        DATA_CRIACAO
    FROM USUARIOS 
    ORDER BY ID
) WHERE ROWNUM <= 5;

-- 9. VERIFICAR COLUNAS ESPECÍFICAS QUE DEVEM EXISTIR
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN 'EXISTE'
        ELSE 'NÃO EXISTE'
    END AS STATUS_COLUNA,
    'ID' AS NOME_COLUNA
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' AND COLUMN_NAME = 'ID'
UNION ALL
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN 'EXISTE'
        ELSE 'NÃO EXISTE'
    END AS STATUS_COLUNA,
    'E_MAIL' AS NOME_COLUNA
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' AND COLUMN_NAME = 'E_MAIL'
UNION ALL
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN 'EXISTE'
        ELSE 'NÃO EXISTE'
    END AS STATUS_COLUNA,
    'USUARIO_ATIVO' AS NOME_COLUNA
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' AND COLUMN_NAME = 'USUARIO_ATIVO'
UNION ALL
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN 'EXISTE'
        ELSE 'NÃO EXISTE'
    END AS STATUS_COLUNA,
    'PIS/PASEP' AS NOME_COLUNA
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' AND COLUMN_NAME = 'PIS/PASEP'
UNION ALL
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN 'EXISTE'
        ELSE 'NÃO EXISTE'
    END AS STATUS_COLUNA,
    'COMISSAO_FUNÇAO' AS NOME_COLUNA
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'USUARIOS' AND COLUMN_NAME = 'COMISSAO_FUNÇAO';

-- 10. RESUMO FINAL
SELECT 
    'VERIFICAÇÃO CONCLUÍDA' AS STATUS,
    SYSDATE AS DATA_VERIFICACAO
FROM DUAL;