-- Script para alterar a estrutura da tabela SETORES
-- Conectar como: protocolo_user/Anderline49@localhost:1521/FREEPDB1

-- 1. Adicionar novos campos
ALTER TABLE SETORES ADD (
    COLUNA1 VARCHAR2(255),
    LOGRADOURO VARCHAR2(255),
    NUMERO VARCHAR2(50),
    BAIRRO VARCHAR2(100),
    CIDADE VARCHAR2(100),
    ESTADO VARCHAR2(2),
    CEP VARCHAR2(10),
    LATITUDE NUMBER(10,8),
    LONGITUDE NUMBER(11,8),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Migrar dados existentes (se houver campo ENDERECO)
-- Comentado pois não sabemos a estrutura atual exata
-- UPDATE SETORES SET LOGRADOURO = ENDERECO WHERE ENDERECO IS NOT NULL;

-- 3. Remover campos antigos (executar apenas após confirmar que não são mais necessários)
-- ALTER TABLE SETORES DROP COLUMN HIERARQUIA_SETOR;
-- ALTER TABLE SETORES DROP COLUMN MUNICIPIO_LOTACAO;
-- ALTER TABLE SETORES DROP COLUMN ENDERECO;

-- 4. Renomear campos de data (se existirem)
-- ALTER TABLE SETORES RENAME COLUMN CREATED_AT TO DATA_CRIACAO;
-- ALTER TABLE SETORES RENAME COLUMN UPDATED_AT TO DATA_ATUALIZACAO;

-- 5. Criar índices para melhor performance
CREATE INDEX IDX_SETORES_CIDADE ON SETORES(CIDADE);
CREATE INDEX IDX_SETORES_ESTADO ON SETORES(ESTADO);
CREATE INDEX IDX_SETORES_CEP ON SETORES(CEP);
CREATE INDEX IDX_SETORES_ATIVO ON SETORES(ATIVO);

-- 6. Comentários nas colunas
COMMENT ON COLUMN SETORES.COLUNA1 IS 'Campo genérico para informações adicionais';
COMMENT ON COLUMN SETORES.LOGRADOURO IS 'Endereço - Logradouro';
COMMENT ON COLUMN SETORES.NUMERO IS 'Endereço - Número';
COMMENT ON COLUMN SETORES.BAIRRO IS 'Endereço - Bairro';
COMMENT ON COLUMN SETORES.CIDADE IS 'Endereço - Cidade';
COMMENT ON COLUMN SETORES.ESTADO IS 'Endereço - Estado (UF)';
COMMENT ON COLUMN SETORES.CEP IS 'Código de Endereçamento Postal';
COMMENT ON COLUMN SETORES.LATITUDE IS 'Coordenada geográfica - Latitude';
COMMENT ON COLUMN SETORES.LONGITUDE IS 'Coordenada geográfica - Longitude';
COMMENT ON COLUMN SETORES.DATA_CRIACAO IS 'Data e hora de criação do registro';
COMMENT ON COLUMN SETORES.DATA_ATUALIZACAO IS 'Data e hora da última atualização';

-- 7. Trigger para atualizar DATA_ATUALIZACAO automaticamente
CREATE OR REPLACE TRIGGER TRG_SETORES_UPDATE_DATE
    BEFORE UPDATE ON SETORES
    FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP;
END;
/

COMMIT;

-- Verificar a estrutura final da tabela
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SETORES' 
ORDER BY COLUMN_ID;