-- Script para alterar a estrutura da tabela SETORES conforme nova estrutura
-- Conectar como: protocolo_user/Anderline49@localhost:1521/FREEPDB1
-- Nova estrutura: ID, CODIGO_SETOR, NOME_SETOR, ORGAO, ATIVO, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TELEFONE, EMAIL, DATA_CRIACAO, DATA_ATUALIZACAO, LATITUDE, LONGITUDE

-- 1. Verificar estrutura atual
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SETORES' 
ORDER BY COLUMN_ID;

-- 2. Adicionar campos que não existem (executar apenas os que não existirem)
-- Verificar quais campos já existem antes de executar cada ALTER TABLE

-- Campo LOGRADOURO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD LOGRADOURO VARCHAR2(255)';
    DBMS_OUTPUT.PUT_LINE('Campo LOGRADOURO adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN -- Column already exists
            DBMS_OUTPUT.PUT_LINE('Campo LOGRADOURO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo NUMERO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD NUMERO VARCHAR2(50)';
    DBMS_OUTPUT.PUT_LINE('Campo NUMERO adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo NUMERO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo COMPLEMENTO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD COMPLEMENTO VARCHAR2(100)';
    DBMS_OUTPUT.PUT_LINE('Campo COMPLEMENTO adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo COMPLEMENTO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo BAIRRO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD BAIRRO VARCHAR2(100)';
    DBMS_OUTPUT.PUT_LINE('Campo BAIRRO adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo BAIRRO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo CIDADE
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD CIDADE VARCHAR2(100)';
    DBMS_OUTPUT.PUT_LINE('Campo CIDADE adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo CIDADE já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo ESTADO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD ESTADO VARCHAR2(2)';
    DBMS_OUTPUT.PUT_LINE('Campo ESTADO adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo ESTADO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo CEP
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD CEP VARCHAR2(10)';
    DBMS_OUTPUT.PUT_LINE('Campo CEP adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo CEP já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo DATA_CRIACAO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
    DBMS_OUTPUT.PUT_LINE('Campo DATA_CRIACAO adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo DATA_CRIACAO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo DATA_ATUALIZACAO
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
    DBMS_OUTPUT.PUT_LINE('Campo DATA_ATUALIZACAO adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo DATA_ATUALIZACAO já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo LATITUDE
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD LATITUDE NUMBER(10,8)';
    DBMS_OUTPUT.PUT_LINE('Campo LATITUDE adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo LATITUDE já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- Campo LONGITUDE
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD LONGITUDE NUMBER(11,8)';
    DBMS_OUTPUT.PUT_LINE('Campo LONGITUDE adicionado');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1430 THEN
            DBMS_OUTPUT.PUT_LINE('Campo LONGITUDE já existe');
        ELSE
            RAISE;
        END IF;
END;
/

-- 3. Criar índices para melhor performance
CREATE INDEX IDX_SETORES_CODIGO ON SETORES(CODIGO_SETOR);
CREATE INDEX IDX_SETORES_NOME ON SETORES(NOME_SETOR);
CREATE INDEX IDX_SETORES_ORGAO ON SETORES(ORGAO);
CREATE INDEX IDX_SETORES_CIDADE ON SETORES(CIDADE);
CREATE INDEX IDX_SETORES_ESTADO ON SETORES(ESTADO);
CREATE INDEX IDX_SETORES_CEP ON SETORES(CEP);
CREATE INDEX IDX_SETORES_ATIVO ON SETORES(ATIVO);

-- 4. Trigger para atualizar DATA_ATUALIZACAO automaticamente
CREATE OR REPLACE TRIGGER TRG_SETORES_UPDATE_DATE
    BEFORE UPDATE ON SETORES
    FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP;
END;
/

-- 5. Comentários nas colunas
COMMENT ON COLUMN SETORES.ID IS 'Identificador único do setor';
COMMENT ON COLUMN SETORES.CODIGO_SETOR IS 'Código do setor';
COMMENT ON COLUMN SETORES.NOME_SETOR IS 'Nome do setor';
COMMENT ON COLUMN SETORES.ORGAO IS 'Órgão ao qual o setor pertence';
COMMENT ON COLUMN SETORES.ATIVO IS 'Status ativo/inativo do setor';
COMMENT ON COLUMN SETORES.LOGRADOURO IS 'Endereço - Logradouro';
COMMENT ON COLUMN SETORES.NUMERO IS 'Endereço - Número';
COMMENT ON COLUMN SETORES.COMPLEMENTO IS 'Endereço - Complemento';
COMMENT ON COLUMN SETORES.BAIRRO IS 'Endereço - Bairro';
COMMENT ON COLUMN SETORES.CIDADE IS 'Endereço - Cidade';
COMMENT ON COLUMN SETORES.ESTADO IS 'Endereço - Estado (UF)';
COMMENT ON COLUMN SETORES.CEP IS 'Código de Endereçamento Postal';
COMMENT ON COLUMN SETORES.TELEFONE IS 'Telefone de contato';
COMMENT ON COLUMN SETORES.EMAIL IS 'E-mail de contato';
COMMENT ON COLUMN SETORES.DATA_CRIACAO IS 'Data e hora de criação do registro';
COMMENT ON COLUMN SETORES.DATA_ATUALIZACAO IS 'Data e hora da última atualização';
COMMENT ON COLUMN SETORES.LATITUDE IS 'Coordenada geográfica - Latitude';
COMMENT ON COLUMN SETORES.LONGITUDE IS 'Coordenada geográfica - Longitude';

COMMIT;

-- 6. Verificar estrutura final
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, COLUMN_ID
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SETORES' 
ORDER BY COLUMN_ID;

-- 7. Verificar alguns registros
SELECT COUNT(*) AS TOTAL_REGISTROS FROM SETORES;