-- =====================================================
-- SCRIPT PARA CORRIGIR ESTRUTURA DA TABELA USUARIOS
-- Para permitir importação dos dados do CSV
-- =====================================================

-- Conectar como protocolo_user
-- CONN protocolo_user/Anderline49@localhost:1521/FREEPDB1

-- 1. ALTERAR USUARIO_ATIVO para aceitar valores numéricos como string
ALTER TABLE USUARIOS MODIFY USUARIO_ATIVO VARCHAR2(1);

-- 2. ALTERAR ULTIMO_LOGIN para aceitar formato de data mais flexível
-- Primeiro, vamos alterar para VARCHAR2 temporariamente para receber os dados
ALTER TABLE USUARIOS MODIFY ULTIMO_LOGIN VARCHAR2(50);

-- 3. AUMENTAR TAMANHO DO CAMPO PIS/PASEP (pode ter valores maiores no CSV)
ALTER TABLE USUARIOS MODIFY "PIS/PASEP" VARCHAR2(20);

-- 4. AUMENTAR TAMANHO DO CAMPO COMISSAO_FUNÇAO
ALTER TABLE USUARIOS MODIFY "COMISSAO_FUNÇAO" VARCHAR2(500);

-- 5. ALTERAR VINCULO_FUNCIONAL para aceitar valores numéricos como string
ALTER TABLE USUARIOS MODIFY VINCULO_FUNCIONAL VARCHAR2(100);

-- 6. AUMENTAR TAMANHOS DE CAMPOS QUE PODEM TER VALORES LONGOS
ALTER TABLE USUARIOS MODIFY ENDERECO VARCHAR2(500);
ALTER TABLE USUARIOS MODIFY CARGO VARCHAR2(200);
ALTER TABLE USUARIOS MODIFY ORGAO VARCHAR2(200);

-- 7. ALTERAR PNE para aceitar valores mais longos temporariamente
ALTER TABLE USUARIOS MODIFY PNE VARCHAR2(10);

-- 8. ALTERAR CAMPOS DE DATA para VARCHAR2 temporariamente para receber formato DD/MM/YYYY
ALTER TABLE USUARIOS MODIFY DATA_NASCIMENTO VARCHAR2(20);
ALTER TABLE USUARIOS MODIFY EXPEDICAO_RG VARCHAR2(20);
ALTER TABLE USUARIOS MODIFY DATA_INI_COMISSAO VARCHAR2(20);

-- 9. AUMENTAR OUTROS CAMPOS QUE PODEM TER VALORES MAIORES
ALTER TABLE USUARIOS MODIFY NOME VARCHAR2(200);
ALTER TABLE USUARIOS MODIFY EMAIL VARCHAR2(150);
ALTER TABLE USUARIOS MODIFY CPF VARCHAR2(20);
ALTER TABLE USUARIOS MODIFY RG VARCHAR2(30);
ALTER TABLE USUARIOS MODIFY TELEFONE VARCHAR2(30);
ALTER TABLE USUARIOS MODIFY CELULAR VARCHAR2(30);

-- =====================================================
-- VERIFICAÇÕES PÓS-ALTERAÇÃO
-- =====================================================

-- Verificar a estrutura atualizada da tabela
DESCRIBE USUARIOS;

-- Contar registros atuais
SELECT COUNT(*) AS TOTAL_REGISTROS_ATUAIS FROM USUARIOS;

COMMIT;

-- =====================================================
-- SCRIPT DE LIMPEZA DE DADOS PÓS-IMPORTAÇÃO
-- (Execute após importar o CSV)
-- =====================================================

/*
-- Após importar o CSV, execute este bloco para limpar e converter os dados:

-- 1. Converter USUARIO_ATIVO de "1"/"0" para "S"/"N"
UPDATE USUARIOS 
SET USUARIO_ATIVO = CASE 
    WHEN USUARIO_ATIVO = '1' THEN 'S'
    WHEN USUARIO_ATIVO = '0' THEN 'N'
    ELSE USUARIO_ATIVO
END
WHERE USUARIO_ATIVO IN ('1', '0');

-- 2. Converter PNE de texto completo para "S"/"N"
UPDATE USUARIOS 
SET PNE = CASE 
    WHEN UPPER(PNE) IN ('SIM', 'S') THEN 'S'
    WHEN UPPER(PNE) IN ('NAO', 'NÃO', 'N') THEN 'N'
    ELSE 'N'
END;

-- 3. Converter datas de DD/MM/YYYY para DATE (se necessário)
-- DATA_NASCIMENTO
UPDATE USUARIOS 
SET DATA_NASCIMENTO = TO_DATE(DATA_NASCIMENTO, 'DD/MM/YYYY')
WHERE DATA_NASCIMENTO IS NOT NULL 
AND LENGTH(DATA_NASCIMENTO) = 10
AND DATA_NASCIMENTO LIKE '__/__/____';

-- EXPEDICAO_RG
UPDATE USUARIOS 
SET EXPEDICAO_RG = TO_DATE(EXPEDICAO_RG, 'DD/MM/YYYY')
WHERE EXPEDICAO_RG IS NOT NULL 
AND LENGTH(EXPEDICAO_RG) = 10
AND EXPEDICAO_RG LIKE '__/__/____';

-- DATA_INI_COMISSAO
UPDATE USUARIOS 
SET DATA_INI_COMISSAO = TO_DATE(DATA_INI_COMISSAO, 'DD/MM/YYYY')
WHERE DATA_INI_COMISSAO IS NOT NULL 
AND LENGTH(DATA_INI_COMISSAO) = 10
AND DATA_INI_COMISSAO LIKE '__/__/____';

-- 4. Limpar campos vazios (converter strings vazias para NULL)
UPDATE USUARIOS SET ULTIMO_LOGIN = NULL WHERE ULTIMO_LOGIN = '';
UPDATE USUARIOS SET "PIS/PASEP" = NULL WHERE "PIS/PASEP" = '';
UPDATE USUARIOS SET "COMISSAO_FUNÇAO" = NULL WHERE "COMISSAO_FUNÇAO" = '';

COMMIT;

-- Verificar os dados após limpeza
SELECT 
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(CASE WHEN USUARIO_ATIVO = 'S' THEN 1 END) AS USUARIOS_ATIVOS,
    COUNT(CASE WHEN PNE = 'S' THEN 1 END) AS USUARIOS_PNE,
    COUNT(CASE WHEN DATA_NASCIMENTO IS NOT NULL THEN 1 END) AS COM_DATA_NASCIMENTO
FROM USUARIOS;
*/

-- =====================================================
-- FIM DO SCRIPT
-- =====================================================