-- Script: create_table_malote.sql
-- Objetivo: Criar a tabela MALOTE no Oracle (FREEPDB1) para armazenar dados dos malotes
-- Schema esperado: protocolo_user
-- Execução (via SQL*Plus):
--   sqlplus protocolo_user/Anderline49@localhost:1521/FREEPDB1 @docs/ScriptsSQL/create_table_malote.sql

WHENEVER SQLERROR EXIT FAILURE

-- Criação da tabela MALOTE com tipos compatíveis com Oracle
CREATE TABLE MALOTE (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

  /* --- Dados do Contrato --- */
  NUMERO_CONTRATO   VARCHAR2(50),
  NUMERO_PERCURSO   VARCHAR2(50),
  CODIGO_EMISSAO    VARCHAR2(50),
  DATA_EMISSAO      DATE,
  DATA_VALIDADE     DATE,

  /* --- Dados do Malote --- */
  NUMERO_MALOTE     VARCHAR2(20),
  CEP_ORIGEM        VARCHAR2(10),
  CEP_DESTINO       VARCHAR2(10),
  IDA               NUMBER(10),
  TAMANHO           CHAR(1),
  DIAS_SERVICO      VARCHAR2(20),
  ESTACAO           VARCHAR2(10),
  DISTRITOS         VARCHAR2(10),
  CODIGO_LATERAL    VARCHAR2(10),
  ATIVO             CHAR(1),
  DATA_CRIACAO      DATE,
  DATA_ATUALIZACAO  DATE,

  /* --- Chave Estrangeira (Relacionamento) --- */
  SETOR_ID          NUMBER(10) NOT NULL,

  /* --- Constraints --- */
  CONSTRAINT PK_MALOTE PRIMARY KEY (ID),
  CONSTRAINT CK_MALOTE_ATIVO CHECK (ATIVO IN ('0','1')),
  CONSTRAINT FK_MALOTE_SETOR FOREIGN KEY (SETOR_ID) REFERENCES SETORES (SETORID)
);

-- Índice auxiliar para FK
CREATE INDEX IDX_MALOTE_SETOR ON MALOTE (SETOR_ID);

-- Comentários (opcional)
COMMENT ON TABLE MALOTE IS 'Tabela de cadastro de malotes (contrato, percurso, destino, setor)';
COMMENT ON COLUMN MALOTE.SETOR_ID IS 'Setor de destino (FK para SETORES.SETORID)';

EXIT SUCCESS