-- DDL da tabela LACRE
-- Schema: protocolo_user (Oracle)
-- Finalidade: suportar a nova aba "Lacre" (geração, distribuição, edição, vinculação e destruição)

-- Opcional: definir o schema atual
ALTER SESSION SET CURRENT_SCHEMA = protocolo_user;

-- Criação da tabela LACRE
CREATE TABLE protocolo_user.LACRE (
  ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CODIGO            VARCHAR2(32)    NOT NULL,
  STATUS            VARCHAR2(20)    NOT NULL,
  SETOR_ID          NUMBER          NULL,
  ENCOMENDA_ID      NUMBER          NULL,
  LOTE_NUMERO       VARCHAR2(20)    NULL,
  MOTIVO_DESTRUICAO VARCHAR2(255)   NULL,
  DATA_CRIACAO      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  DATA_ATUALIZACAO  TIMESTAMP       NULL,

  CONSTRAINT UK_LACRE_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_LACRE_STATUS CHECK (STATUS IN (
    'disponivel',
    'reservado',
    'vinculado',
    'utilizado',
    'extraviado',
    'danificado',
    'destruido'
  ))
);

-- Chave estrangeira para setores (ajuste o nome da tabela/coluna se necessário)
ALTER TABLE protocolo_user.LACRE
  ADD CONSTRAINT FK_LACRE_SETOR
  FOREIGN KEY (SETOR_ID) REFERENCES protocolo_user.SETORES (ID);

-- Chave estrangeira para encomendas (ajuste o nome da tabela/coluna se necessário)
-- Se o nome da tabela for ENCOMENDA/ENCOMENDAS diferente, ajuste aqui antes de aplicar em produção
ALTER TABLE protocolo_user.LACRE
  ADD CONSTRAINT FK_LACRE_ENCOMENDA
  FOREIGN KEY (ENCOMENDA_ID) REFERENCES protocolo_user.ENCOMENDAS (ID);

-- Índices para melhorar buscas/filtragens frequentes na aba Lacre
CREATE INDEX protocolo_user.IDX_LACRE_STATUS ON protocolo_user.LACRE (STATUS);
CREATE INDEX protocolo_user.IDX_LACRE_SETOR  ON protocolo_user.LACRE (SETOR_ID);
CREATE INDEX protocolo_user.IDX_LACRE_LOTE   ON protocolo_user.LACRE (LOTE_NUMERO);
CREATE INDEX protocolo_user.IDX_LACRE_CODIGO ON protocolo_user.LACRE (CODIGO);

-- Trigger para atualizar DATA_ATUALIZACAO em updates
CREATE OR REPLACE TRIGGER protocolo_user.TRG_LACRE_UPD_TS
BEFORE UPDATE ON protocolo_user.LACRE
FOR EACH ROW
BEGIN
  :NEW.DATA_ATUALIZACAO := SYSTIMESTAMP;
END;
/

-- Comentários de documentação
COMMENT ON TABLE  protocolo_user.LACRE IS 'Tabela de lacres: geração, distribuição, vinculação a encomenda e destruição';
COMMENT ON COLUMN protocolo_user.LACRE.ID                IS 'Identificador único (IDENTITY)';
COMMENT ON COLUMN protocolo_user.LACRE.CODIGO            IS 'Código único do lacre (ex.: LACRE000001)';
COMMENT ON COLUMN protocolo_user.LACRE.STATUS            IS 'Status do lacre (disponivel, reservado, vinculado, utilizado, extraviado, danificado, destruido)';
COMMENT ON COLUMN protocolo_user.LACRE.SETOR_ID          IS 'Setor que recebeu o lacre (distribuição)';
COMMENT ON COLUMN protocolo_user.LACRE.ENCOMENDA_ID      IS 'Encomenda vinculada ao lacre (quando aplicável)';
COMMENT ON COLUMN protocolo_user.LACRE.LOTE_NUMERO       IS 'Número do lote usado na geração';
COMMENT ON COLUMN protocolo_user.LACRE.MOTIVO_DESTRUICAO IS 'Motivo da destruição (quando STATUS=destruido)';
COMMENT ON COLUMN protocolo_user.LACRE.DATA_CRIACAO      IS 'Timestamp de criação do registro';
COMMENT ON COLUMN protocolo_user.LACRE.DATA_ATUALIZACAO  IS 'Timestamp da última atualização do registro';

-- Observação: o histórico de ações do lacre (data/ação/detalhes) é melhor modelado
-- em uma tabela própria (ex.: LACRE_HISTORICO) para auditoria completa.