-- Diagnóstico de constraints e possíveis duplicidades na tabela SETORES
SET LINESIZE 200;
SET PAGESIZE 100;
SET SERVEROUTPUT ON;

PROMPT ===== Verificando constraints da tabela SETORES =====
COLUMN CONSTRAINT_NAME FORMAT A30;
COLUMN CONSTRAINT_TYPE FORMAT A10;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'SETORES'
ORDER BY CONSTRAINT_TYPE, CONSTRAINT_NAME;

PROMPT ===== Colunas das constraints (UNIQUE/PK) =====
COLUMN COLUMN_NAME FORMAT A30;
SELECT cc.CONSTRAINT_NAME, cc.COLUMN_NAME
FROM USER_CONS_COLUMNS cc
JOIN USER_CONSTRAINTS c ON c.CONSTRAINT_NAME = cc.CONSTRAINT_NAME
WHERE c.TABLE_NAME = 'SETORES'
  AND c.CONSTRAINT_TYPE IN ('U','P')
ORDER BY cc.CONSTRAINT_NAME, cc.POSITION;

PROMPT ===== Índices na tabela SETORES =====
COLUMN INDEX_NAME FORMAT A30;
COLUMN UNIQUENESS FORMAT A10;
SELECT INDEX_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME = 'SETORES'
ORDER BY INDEX_NAME;

PROMPT ===== Amostra de registros em SETORES =====
COLUMN ID FORMAT 999999;
COLUMN CODIGO_SETOR FORMAT A25;
COLUMN NOME_SETOR FORMAT A50;
SELECT ID, CODIGO_SETOR, NOME_SETOR, ORGAO, ATIVO
FROM SETORES
FETCH FIRST 20 ROWS ONLY;

PROMPT ===== Verificando duplicidades por CODIGO_SETOR =====
SELECT CODIGO_SETOR, COUNT(*) AS QTD
FROM SETORES
GROUP BY CODIGO_SETOR
HAVING COUNT(*) > 1
ORDER BY QTD DESC;

PROMPT ===== Verificando duplicidades por NOME_SETOR (se aplicável) =====
SELECT NOME_SETOR, COUNT(*) AS QTD
FROM SETORES
GROUP BY NOME_SETOR
HAVING COUNT(*) > 1
ORDER BY QTD DESC;

PROMPT ===== Detalhes de colunas NOT NULL (para validar inserts) =====
COLUMN NULLABLE FORMAT A8;
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'SETORES'
ORDER BY COLUMN_ID;

PROMPT ===== Fim do diagnóstico =====