-- Garante unicidade de CONFIGURACOES.CHAVE se não houver duplicidades
SET SERVEROUTPUT ON
DECLARE
  v_dups NUMBER := 0;
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_dups FROM (
    SELECT CHAVE FROM CONFIGURACOES GROUP BY CHAVE HAVING COUNT(*) > 1
  );

  SELECT COUNT(*) INTO v_exists FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'CONFIGURACOES'
     AND CONSTRAINT_NAME = 'UK_CONFIGURACOES_CHAVE';

  IF v_dups > 0 THEN
    DBMS_OUTPUT.PUT_LINE('Não foi possível criar a constraint. Existem duplicidades em CHAVE.');
    DBMS_OUTPUT.PUT_LINE('Revise as duplicidades com: SELECT CHAVE, COUNT(*) FROM CONFIGURACOES GROUP BY CHAVE HAVING COUNT(*) > 1;');
  ELSE
    IF v_exists = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE CONFIGURACOES ADD CONSTRAINT UK_CONFIGURACOES_CHAVE UNIQUE (CHAVE)';
      DBMS_OUTPUT.PUT_LINE('Constraint criada: UK_CONFIGURACOES_CHAVE');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Constraint já existe: UK_CONFIGURACOES_CHAVE');
    END IF;
  END IF;
END;
/
PROMPT Fim do script de unicidade de CHAVE em CONFIGURACOES.