-- Verificar estrutura atual da tabela SETORES
SELECT 'ESTRUTURA ATUAL DA TABELA SETORES:' AS INFO FROM DUAL;
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, COLUMN_ID
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SETORES' 
ORDER BY COLUMN_ID;

-- Habilitar output do DBMS
SET SERVEROUTPUT ON;

-- Adicionar campos que não existem
SELECT 'ADICIONANDO NOVOS CAMPOS...' AS INFO FROM DUAL;

-- Campo LOGRADOURO
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'LOGRADOURO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD LOGRADOURO VARCHAR2(255)';
        DBMS_OUTPUT.PUT_LINE('Campo LOGRADOURO adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo LOGRADOURO já existe');
    END IF;
END;
/

-- Campo NUMERO
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'NUMERO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD NUMERO VARCHAR2(50)';
        DBMS_OUTPUT.PUT_LINE('Campo NUMERO adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo NUMERO já existe');
    END IF;
END;
/

-- Campo COMPLEMENTO
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'COMPLEMENTO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD COMPLEMENTO VARCHAR2(100)';
        DBMS_OUTPUT.PUT_LINE('Campo COMPLEMENTO adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo COMPLEMENTO já existe');
    END IF;
END;
/

-- Campo BAIRRO
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'BAIRRO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD BAIRRO VARCHAR2(100)';
        DBMS_OUTPUT.PUT_LINE('Campo BAIRRO adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo BAIRRO já existe');
    END IF;
END;
/

-- Campo CIDADE
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'CIDADE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD CIDADE VARCHAR2(100)';
        DBMS_OUTPUT.PUT_LINE('Campo CIDADE adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo CIDADE já existe');
    END IF;
END;
/

-- Campo ESTADO
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'ESTADO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD ESTADO VARCHAR2(2)';
        DBMS_OUTPUT.PUT_LINE('Campo ESTADO adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo ESTADO já existe');
    END IF;
END;
/

-- Campo CEP
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'CEP';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD CEP VARCHAR2(10)';
        DBMS_OUTPUT.PUT_LINE('Campo CEP adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo CEP já existe');
    END IF;
END;
/

-- Campo DATA_CRIACAO
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'DATA_CRIACAO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
        DBMS_OUTPUT.PUT_LINE('Campo DATA_CRIACAO adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo DATA_CRIACAO já existe');
    END IF;
END;
/

-- Campo DATA_ATUALIZACAO
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'DATA_ATUALIZACAO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
        DBMS_OUTPUT.PUT_LINE('Campo DATA_ATUALIZACAO adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo DATA_ATUALIZACAO já existe');
    END IF;
END;
/

-- Campo LATITUDE
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'LATITUDE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD LATITUDE NUMBER(10,8)';
        DBMS_OUTPUT.PUT_LINE('Campo LATITUDE adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo LATITUDE já existe');
    END IF;
END;
/

-- Campo LONGITUDE
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'SETORES' AND COLUMN_NAME = 'LONGITUDE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SETORES ADD LONGITUDE NUMBER(11,8)';
        DBMS_OUTPUT.PUT_LINE('Campo LONGITUDE adicionado');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Campo LONGITUDE já existe');
    END IF;
END;
/

-- Criar trigger para atualizar DATA_ATUALIZACAO
CREATE OR REPLACE TRIGGER TRG_SETORES_UPDATE_DATE
    BEFORE UPDATE ON SETORES
    FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := CURRENT_TIMESTAMP;
END;
/

SELECT 'Trigger TRG_SETORES_UPDATE_DATE criado/atualizado' AS INFO FROM DUAL;

-- Commit das alterações
COMMIT;

-- Verificar estrutura final
SELECT 'ESTRUTURA FINAL DA TABELA SETORES:' AS INFO FROM DUAL;
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, COLUMN_ID
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SETORES' 
ORDER BY COLUMN_ID;

-- Verificar total de registros
SELECT 'TOTAL DE REGISTROS:' AS INFO FROM DUAL;
SELECT COUNT(*) AS TOTAL_REGISTROS FROM SETORES;

SELECT 'ALTERAÇÕES CONCLUÍDAS COM SUCESSO!' AS INFO FROM DUAL;

EXIT;