-- Consulta o valor atual de HUB_SETOR_ID em CONFIGURACOES
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 0
SET FEEDBACK OFF
PROMPT HUB_SETOR_ID atual:
SELECT VALOR FROM CONFIGURACOES WHERE CHAVE = 'HUB_SETOR_ID';
PROMPT Fim da consulta HUB_SETOR_ID.