-- Script para recriar a tabela USUARIOS com as colunas exatas especificadas
-- Ordem das colunas conforme solicitado pelo usuário

-- Primeiro, tentar fazer commit para liberar possíveis locks
COMMIT;

-- Dropar a tabela atual (se conseguir)
DROP TABLE USUARIOS CASCADE CONSTRAINTS;

-- Criar a nova tabela USUARIOS com as 55 colunas na ordem exata
CREATE TABLE USUARIOS (
    ID NUMBER,
    SETOR_ID NUMBER,
    ROLE VARCHAR2(50),
    SENHA VARCHAR2(255),
    USUARIO_ATIVO VARCHAR2(1),
    ULTIMO_LOGIN VARCHAR2(50),
    TENTATIVAS_LOGIN NUMBER,
    DATA_CRIACAO VARCHAR2(50),
    DATA_ATUALIZACAO VARCHAR2(50),
    BLOQUEADO_ATE VARCHAR2(50),
    NOME VARCHAR2(255),
    MATRICULA VARCHAR2(50),
    VINCULO_FUNCIONAL NUMBER,
    CPF VARCHAR2(20),
    "PIS/PASEP" VARCHAR2(20),
    SEXO VARCHAR2(1),
    ESTADO_CIVIL VARCHAR2(50),
    DATA_NASCIMENTO VARCHAR2(50),
    PAI VARCHAR2(255),
    MAE VARCHAR2(255),
    RG VARCHAR2(50),
    TIPO_RG VARCHAR2(50),
    ORGAO_EXPEDITOR VARCHAR2(50),
    UF_RG VARCHAR2(2),
    EXPEDICAO_RG VARCHAR2(50),
    CIDADE_NASCIMENTO VARCHAR2(100),
    UF_NASCIMENTO VARCHAR2(2),
    TIPO_SANGUINEO VARCHAR2(10),
    RACA_COR VARCHAR2(50),
    PNE VARCHAR2(10),
    TIPO_VINCULO VARCHAR2(100),
    CATEGORIA VARCHAR2(100),
    REGIME_JURIDICO VARCHAR2(100),
    REGIME_PREVIDENCIARIO VARCHAR2(100),
    EVENTO_TIPO VARCHAR2(100),
    FORMA_PROVIMENTO VARCHAR2(100),
    CODIGO_CARGO NUMBER,
    CARGO VARCHAR2(255),
    ESCOLARIDADE_CARGO VARCHAR2(100),
    ESCOLARIDADE_SERVIDOR VARCHAR2(100),
    FORMACAO_PROFISSIONAL_1 VARCHAR2(255),
    FORMACAO_PROFISSIONAL_2 VARCHAR2(255),
    JORNADA NUMBER,
    NIVEL_REFERENCIA VARCHAR2(50),
    "COMISSAO_FUNÇAO" VARCHAR2(255),
    DATA_INI_COMISSAO VARCHAR2(50),
    TELEFONE VARCHAR2(20),
    ENDERECO VARCHAR2(255),
    NUMERO_ENDERECO VARCHAR2(20),
    COMPLEMENTO_ENDERECO VARCHAR2(100),
    BAIRRO_ENDERECO VARCHAR2(100),
    CIDADE_ENDERECO VARCHAR2(100),
    UF_ENDERECO VARCHAR2(2),
    CEP_ENDERECO VARCHAR2(10),
    E_MAIL VARCHAR2(255)
);

-- Confirmar a criação
COMMIT;

-- Verificar a estrutura da tabela criada
DESC USUARIOS;