-- Validação de CEPs: MALOTE vs SETORES
-- Schema: protocolo_user @ FREEPDB1
-- Utilize SQL*Plus para executar:
-- sqlplus protocolo_user/Anderline49@localhost:1521/FREEPDB1

-- 1) Conferir divergências de CEP entre MALOTE e os SETORES vinculados
SELECT
  m.ID,
  m.NUMERO_MALOTE,
  m.SETOR_ORIGEM_ID,
  m.SETOR_DESTINO_ID,
  m.CEP_ORIGEM,
  m.CEP_DESTINO,
  so.NOME_SETOR AS SETOR_ORIGEM,
  so.CEP        AS CEP_ORIGEM_SETOR,
  sd.NOME_SETOR AS SETOR_DESTINO,
  sd.CEP        AS CEP_DESTINO_SETOR,
  CASE WHEN m.CEP_ORIGEM = so.CEP THEN 'OK' ELSE 'DIVERGENTE' END AS CEP_ORIGEM_STATUS,
  CASE WHEN m.CEP_DESTINO = sd.CEP THEN 'OK' ELSE 'DIVERGENTE' END AS CEP_DESTINO_STATUS
FROM MALOTE m
LEFT JOIN SETORES so ON so.ID = m.SETOR_ORIGEM_ID
LEFT JOIN SETORES sd ON sd.ID = m.SETOR_DESTINO_ID
ORDER BY m.ID DESC;

-- 2) Malotes com CEPs ausentes ou setores não vinculados
SELECT
  m.ID,
  m.NUMERO_MALOTE,
  m.SETOR_ORIGEM_ID,
  m.SETOR_DESTINO_ID,
  m.CEP_ORIGEM,
  m.CEP_DESTINO
FROM MALOTE m
WHERE (m.CEP_ORIGEM IS NULL OR TRIM(m.CEP_ORIGEM) = '')
   OR (m.CEP_DESTINO IS NULL OR TRIM(m.CEP_DESTINO) = '')
   OR (m.SETOR_ORIGEM_ID IS NULL)
   OR (m.SETOR_DESTINO_ID IS NULL)
ORDER BY m.ID DESC;

-- 3) Amostra simples de malotes para conferência manual
SELECT ID, NUMERO_MALOTE, CEP_ORIGEM, CEP_DESTINO, SETOR_ORIGEM_ID, SETOR_DESTINO_ID
FROM MALOTE
ORDER BY ID DESC FETCH FIRST 50 ROWS ONLY;

EXIT SUCCESS