-- Script para verificar o estado atual da tabela CONFIGURACOES_AUTENTICACAO
-- Verificando todas as configurações de autenticação

SELECT 
    ID,
    TIPO_AUTENTICACAO,
    ATIVO,
    CONFIGURACAO,
    DATA_CRIACAO,
    DATA_ATUALIZACAO
FROM CONFIGURACOES_AUTENTICACAO
ORDER BY TIPO_AUTENTICACAO;

-- Verificando especificamente LDAP e MOCK
SELECT 
    TIPO_AUTENTICACAO,
    ATIVO,
    CASE 
        WHEN ATIVO = 1 THEN 'ATIVO'
        WHEN ATIVO = 0 THEN 'INATIVO'
        ELSE 'INDEFINIDO'
    END AS STATUS_DESCRICAO
FROM CONFIGURACOES_AUTENTICACAO
WHERE TIPO_AUTENTICACAO IN ('LDAP', 'MOCK')
ORDER BY TIPO_AUTENTICACAO;

EXIT;