-- Script para verificar estrutura da tabela SETORES
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SETORES' 
ORDER BY COLUMN_ID;

-- Verificar total de registros
SELECT COUNT(*) AS TOTAL_REGISTROS FROM SETORES;

-- Verificar alguns registros com delegacia
SELECT ID, CODIGO_SETOR, NOME_SETOR, ORGAO, ATIVO 
FROM SETORES 
WHERE UPPER(NOME_SETOR) LIKE '%DELEGACIA%' 
ORDER BY NOME_SETOR;

EXIT;